import type { CharacterConfig } from "../types";
import { coreStats } from "../core-stats";

export const travelerElectro: CharacterConfig = {
  id: "traveler-electro",
  name: "Traveler (Electro)",
  rarity: 5,
  element: "Electro",
  weapon: "Sword",
  scalingSource: "atk",
  ascensionStat: { label: "ATK%", maxValue: 24.0 },
  dmgBonusLabel: "Electro DMG Bonus%",
  stats: coreStats("ATK%"),
  talents: [
    {
      type: "normal",
      name: "Normal Attack — Foreign Thundershock",
      hits: [
        { key: "1-hit", name: "1-Hit DMG", scaling: "atk", hitCategory: "normal", element: "Physical" },
        { key: "2-hit", name: "2-Hit DMG", scaling: "atk", hitCategory: "normal", element: "Physical" },
        { key: "3-hit", name: "3-Hit DMG", scaling: "atk", hitCategory: "normal", element: "Physical" },
        { key: "4-hit", name: "4-Hit DMG", scaling: "atk", hitCategory: "normal", element: "Physical" },
        { key: "5-hit", name: "5-Hit DMG", scaling: "atk", hitCategory: "normal", element: "Physical" },
        { key: "charged-1", name: "Charged Attack (Hit 1)", scaling: "atk", hitCategory: "charged", element: "Physical" },
        { key: "charged-2-aether", name: "Charged Attack (Hit 2 — Aether)", scaling: "atk", hitCategory: "charged", element: "Physical" },
        { key: "charged-2-lumine", name: "Charged Attack (Hit 2 — Lumine)", scaling: "atk", hitCategory: "charged", element: "Physical" },
        { key: "plunge", name: "Plunge DMG", scaling: "atk", hitCategory: "plunge", element: "Physical" },
        { key: "low-plunge", name: "Low Plunge DMG", scaling: "atk", hitCategory: "plunge", element: "Physical" },
        { key: "high-plunge", name: "High Plunge DMG", scaling: "atk", hitCategory: "plunge", element: "Physical" },
      ]
    },
    {
      type: "skill",
      name: "Elemental Skill — Lightning Blade",
      hits: [
        { key: "skill-dmg", name: "Skill DMG", scaling: "atk", hitCategory: "skill", element: "Electro" },
      ]
    },
    {
      type: "burst",
      name: "Elemental Burst — Bellowing Thunder",
      hits: [
        { key: "falling-thunder", name: "Falling Thunder DMG", scaling: "atk", hitCategory: "burst", element: "Electro" },
        { key: "falling-thunder-3rd", name: "3rd Falling Thunder DMG (C6)", scaling: "atk", hitCategory: "burst", element: "Electro", minConstellation: 6 },
      ]
    }
  ],
  mechanicDefs: [
    {
      id: "c2-electro-shred",
      label: "C2 Violet Vehemence (-15% Electro RES)",
      control: "toggle",
      defaultValue: 1,
      hint: "When Falling Thunder hits an opponent, decreases Electro RES by 15%."
    }
  ],
  mechanics: [
    "Thunderflash (A1): Increases Energy restored by Abundance Amulets.",
    "Resounding Roar (A4): Increases ER provided by Abundance Amulets based on 10% of Traveler's ER.",
    "Violet Vehemence (C2): Decreases Electro RES by 15% on Falling Thunder hit.",
    "World-Shaking Thunder (C6): Every 3rd Falling Thunder deals +100% DMG."
  ],
  constellations: [
    { level: 1, name: "Spring Thunder of Thunderclap", description: "Increases Abundance Amulets generated by Lightning Blade to 3.", effects: [{ type: "informational" }] },
    { level: 2, name: "Violet Vehemence", description: "Decreases Electro RES by 15% on Falling Thunder hit.", effects: [{ type: "informational" }] },
    { level: 3, name: "Distant Roar", description: "Increases the Level of Bellowing Thunder by 3.", effects: [{ type: "talent_level_bonus", talentType: "burst" }] },
    { level: 4, name: "Fickle Clouds", description: "Abundance Amulet restores additional Energy if Energy is below 35%.", effects: [{ type: "informational" }] },
    { level: 5, name: "Clap of Thunder", description: "Increases the Level of Lightning Blade by 3.", effects: [{ type: "talent_level_bonus", talentType: "skill" }] },
    { level: 6, name: "World-Shaking Thunder", description: "Every 3rd Falling Thunder deals +100% DMG.", effects: [{ type: "informational" }] }
  ],
  support: {
    description: "Electro battery and support providing team energy generation via Abundance Amulets and -15% Electro RES shred via Violet Vehemence (C2).",
    buffExplanations: [
      {
        name: "C2: Violet Vehemence",
        brief: "-15% Electro RES Shred",
        full: "When Falling Thunder created by Bellowing Thunder hits an opponent, it decreases their Electro RES by 15% for 8s.",
        category: "elemental",
      },
    ],
    statFields: [
      { key: "atk.base", label: "Base ATK", defaultValue: "700" },
      { key: "critRate", label: "CRIT Rate", defaultValue: "60" },
      { key: "critDmg", label: "CRIT DMG", defaultValue: "120" },
    ],
    buffs: [
      {
        stat: "enemyRes",
        label: "Electro RES Shred (Electro MC C2)",
        compute: (ctx) => (ctx.constellationLevel >= 2 && (ctx.inputs["c2-electro-shred"] ?? 1) > 0 ? -15 : 0),
      },
    ],
    formatBriefStats: (ctx) => {
      const fmt = (n: number) => n.toLocaleString("en-US", { maximumFractionDigits: 1 });
      return [
        { label: "Base ATK", value: fmt(ctx.baseAtk) },
        { label: "CRIT", value: `${fmt(ctx.critRate)}% / ${fmt(ctx.critDmg)}%` },
      ];
    },
  },
};
