import type { CharacterConfig } from "../types";
import { coreStats } from "../core-stats";

export const travelerGeo: CharacterConfig = {
  id: "traveler-geo",
  name: "Traveler (Geo)",
  rarity: 5,
  element: "Geo",
  weapon: "Sword",
  scalingSource: "atk",
  ascensionStat: { label: "ATK%", maxValue: 24.0 },
  dmgBonusLabel: "Geo DMG Bonus%",
  stats: coreStats("ATK%"),
  talents: [
    {
      type: "normal",
      name: "Normal Attack — Foreign Rockblade",
      hits: [
        { key: "1-hit", name: "1-Hit DMG", scaling: "atk", hitCategory: "normal", element: "Physical" },
        { key: "2-hit", name: "2-Hit DMG", scaling: "atk", hitCategory: "normal", element: "Physical" },
        { key: "3-hit", name: "3-Hit DMG", scaling: "atk", hitCategory: "normal", element: "Physical" },
        { key: "4-hit", name: "4-Hit DMG", scaling: "atk", hitCategory: "normal", element: "Physical" },
        { key: "5-hit", name: "5-Hit DMG", scaling: "atk", hitCategory: "normal", element: "Physical" },
        { key: "charged-1", name: "Charged Attack (Hit 1)", scaling: "atk", hitCategory: "charged", element: "Physical" },
        { key: "charged-2-aether", name: "Charged Attack (Hit 2 — Aether)", scaling: "atk", hitCategory: "charged", element: "Physical" },
        { key: "charged-2-lumine", name: "Charged Attack (Hit 2 — Lumine)", scaling: "atk", hitCategory: "charged", element: "Physical" },
        { key: "rockslide", name: "Frenzied Rockslide (A4 Passive)", scaling: "atk", hitCategory: "normal", element: "Geo" },
        { key: "plunge", name: "Plunge DMG", scaling: "atk", hitCategory: "plunge", element: "Physical" },
        { key: "low-plunge", name: "Low Plunge DMG", scaling: "atk", hitCategory: "plunge", element: "Physical" },
        { key: "high-plunge", name: "High Plunge DMG", scaling: "atk", hitCategory: "plunge", element: "Physical" },
      ]
    },
    {
      type: "skill",
      name: "Elemental Skill — Starfell Sword",
      hits: [
        { key: "skill-dmg", name: "Skill DMG", scaling: "atk", hitCategory: "skill", element: "Geo" },
        { key: "c2-explosion", name: "Meteorite Explosion DMG (C2)", scaling: "atk", hitCategory: "skill", element: "Geo" },
      ]
    },
    {
      type: "burst",
      name: "Elemental Burst — Wake of Earth",
      hits: [
        { key: "shockwave-dmg", name: "Shockwave DMG (per hit)", scaling: "atk", hitCategory: "burst", element: "Geo" },
      ]
    }
  ],
  mechanicDefs: [
    {
      id: "c1-crit-rate",
      label: "C1 Invincible Wall (+10% CRIT Rate inside Burst zone)",
      control: "toggle",
      defaultValue: 1,
      hint: "Party members within the radius of Wake of Earth have CRIT Rate increased by 10%."
    }
  ],
  mechanics: [
    "Shattered Darkrock (A1): Reduces Starfell Sword CD by 2s.",
    "Frenzied Rockslide (A4): The final hit of a Normal Attack combo deals 60% of ATK as AoE Geo DMG.",
    "Invincible Wall (C1): Party members within the radius of Wake of Earth have CRIT Rate increased by 10%.",
    "Rockcore Meltdown (C2): When a Meteorite created by Starfell Sword is destroyed, it explodes dealing additional AoE Geo DMG."
  ],
  constellations: [
    { level: 1, name: "Invincible Wall", description: "Party members within the radius of Wake of Earth have CRIT Rate increased by 10%.", effects: [{ type: "informational" }] },
    { level: 2, name: "Rockcore Meltdown", description: "When a Meteorite created by Starfell Sword is destroyed, it explodes dealing additional AoE Geo DMG.", effects: [{ type: "informational" }] },
    { level: 3, name: "Will of the Rock", description: "Increases the Level of Wake of Earth by 3.", effects: [{ type: "talent_level_bonus", talentType: "burst" }] },
    { level: 4, name: "Reaction Force", description: "Shockwaves generated by Wake of Earth restore 5 Energy.", effects: [{ type: "informational" }] },
    { level: 5, name: "Meteorite Impact", description: "Increases the Level of Starfell Sword by 3.", effects: [{ type: "talent_level_bonus", talentType: "skill" }] },
    { level: 6, name: "Scoured Unrest", description: "Extends Wake of Earth duration by 5s.", effects: [{ type: "informational" }] }
  ],
  support: {
    description: "Geo support providing construct utility and +10% party CRIT Rate inside Wake of Earth via Invincible Wall (C1).",
    buffExplanations: [
      {
        name: "C1: Invincible Wall",
        brief: "+10% CRIT Rate inside Burst",
        full: "Party members within the radius of Wake of Earth have their CRIT Rate increased by 10% and have increased resistance to interruption.",
        category: "dmg_bonus",
      },
    ],
    statFields: [
      { key: "atk.base", label: "Base ATK", defaultValue: "700" },
      { key: "critRate", label: "CRIT Rate", defaultValue: "60" },
      { key: "critDmg", label: "CRIT DMG", defaultValue: "120" },
    ],
    buffs: [
      {
        stat: "critRate",
        label: "CRIT Rate (Geo MC C1)",
        compute: (ctx) => (ctx.constellationLevel >= 1 && (ctx.inputs["c1-crit-rate"] ?? 1) > 0 ? 10 : 0),
      },
    ],
    formatBriefStats: (ctx) => {
      const fmt = (n: number) => n.toLocaleString("en-US", { maximumFractionDigits: 1 });
      return [
        { label: "Base ATK", value: fmt(ctx.baseAtk) },
        { label: "CRIT", value: `${fmt(ctx.critRate)}% / ${fmt(ctx.critDmg)}%` },
      ];
    },
  },
};
