import fs from "fs";
import path from "path";

// Additional weapons for Swords (to reach 55)
const EXTRA_SWORDS = [
  {
    id: "calamity-of-eshu",
    varName: "calamityOfEshu",
    name: "Calamity of Eshu",
    type: "Sword",
    rarity: 4,
    baseAtk: 565,
    lvl1BaseAtk: 44,
    subStat: { type: "atkPct", label: "ATK%", value: 27.6, baseValue: 6.0 },
    passiveName: "Pure and True",
    passiveDesc: "When HP is above 70%, increases Normal and Charged Attack DMG by 20~40% and Normal and Charged Attack CRIT Rate by 8~16%.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [
      { id: "eshu-hp-70", label: "HP >= 70%", control: "toggle", defaultValue: 1, hint: "+20~40% NA/CA DMG and +8~16% NA/CA CRIT Rate" },
    ],
    buffs: [
      { id: "eshu-na-ca-dmg", label: "Normal/Charged Attack DMG Bonus (Calamity of Eshu)", stat: "normalDmgBonus", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, conditionKey: "eshu-hp-70", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['eshu-hp-70'] ?? '1') === '1' || Number(ctx.inputs?.['eshu-hp-70'] ?? 1) > 0; return on ? [20, 25, 30, 35, 40][r - 1] : 0; }" },
      { id: "eshu-ca-dmg", label: "Charged Attack DMG Bonus (Calamity of Eshu)", stat: "chargedDmgBonus", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, conditionKey: "eshu-hp-70", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['eshu-hp-70'] ?? '1') === '1' || Number(ctx.inputs?.['eshu-hp-70'] ?? 1) > 0; return on ? [20, 25, 30, 35, 40][r - 1] : 0; }" },
    ],
  },
  {
    id: "symphonists-cadenza",
    varName: "symphonistsCadenza",
    name: "Symphonist's Cadenza",
    type: "Sword",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 33.1, baseValue: 7.2 },
    passiveName: "Harmonic Movement",
    passiveDesc: "Increases All Elemental DMG Bonus by 12~24%. Normal and Charged Attacks dealing Elemental DMG grant +16~32% ATK for 10s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "symphonist-elem-dmg", label: "All Elemental DMG Bonus (Symphonist's Cadenza)", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "symphonist-atk", label: "ATK% (Symphonist's Cadenza)", stat: "atk", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([16, 20, 24, 28, 32][r - 1] / 100) * ctx.baseAtk" },
    ],
  },
  {
    id: "rainbows-end",
    varName: "rainbowsEnd",
    name: "Rainbow's End",
    type: "Sword",
    rarity: 4,
    baseAtk: 510,
    lvl1BaseAtk: 42,
    subStat: { type: "em", label: "Elemental Mastery", value: 165, baseValue: 36 },
    passiveName: "Prismatic Wave",
    passiveDesc: "After triggering an Elemental Reaction, Elemental Skill DMG is increased by 16~32% for 8s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "rainbow-skill-dmg", label: "Elemental Skill DMG Bonus (Rainbow's End)", stat: "skillDmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "song-of-the-dappled-moon",
    varName: "songOfTheDappledMoon",
    name: "Song of the Dappled Moon",
    type: "Sword",
    rarity: 4,
    baseAtk: 565,
    lvl1BaseAtk: 44,
    subStat: { type: "energyRecharge", label: "Energy Recharge%", value: 30.6, baseValue: 6.7 },
    passiveName: "Lunar Resonance",
    passiveDesc: "Using an Elemental Burst increases All Elemental DMG Bonus by 12~24% for 12s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "dappled-moon-elem-dmg", label: "All Elemental DMG Bonus (Song of the Dappled Moon)", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
    ],
  },
  {
    id: "heartpiercer-sword",
    varName: "heartpiercerSword",
    name: "Heartpiercer",
    type: "Sword",
    rarity: 4,
    baseAtk: 510,
    lvl1BaseAtk: 42,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 27.6, baseValue: 6.0 },
    passiveName: "Keen Edge",
    passiveDesc: "CRIT Hits increase ATK by 16~32% for 6s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "heartpiercer-atk", label: "ATK% (Heartpiercer)", stat: "atk", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([16, 20, 24, 28, 32][r - 1] / 100) * ctx.baseAtk" },
    ],
  },
  {
    id: "wave-cutting-gin",
    varName: "waveCuttingGin",
    name: "Wave-Cutting Gin",
    type: "Sword",
    rarity: 4,
    baseAtk: 565,
    lvl1BaseAtk: 44,
    subStat: { type: "atkPct", label: "ATK%", value: 27.6, baseValue: 6.0 },
    passiveName: "Tidal Slash",
    passiveDesc: "Normal Attack DMG is increased by 16~32%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "wave-cutting-na-dmg", label: "Normal Attack DMG Bonus (Wave-Cutting Gin)", stat: "normalDmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "flute-of-the-crescent-moon",
    varName: "fluteOfTheCrescentMoon",
    name: "Flute of the Crescent Moon",
    type: "Sword",
    rarity: 4,
    baseAtk: 510,
    lvl1BaseAtk: 42,
    subStat: { type: "hpPct", label: "HP%", value: 41.3, baseValue: 9.0 },
    passiveName: "Crescent Song",
    passiveDesc: "Max HP is increased by 16~32%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "flute-crescent-hp", label: "HP% (Flute of the Crescent Moon)", stat: "hp", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, isPercent: true, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "sky-rending-talon",
    varName: "skyRendingTalon",
    name: "Sky-Rending Talon",
    type: "Sword",
    rarity: 4,
    baseAtk: 565,
    lvl1BaseAtk: 44,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 36.8, baseValue: 8.0 },
    passiveName: "Rending Strike",
    passiveDesc: "Elemental Skill hits increase Charged Attack DMG by 20~40% for 6s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "sky-rending-ca-dmg", label: "Charged Attack DMG Bonus (Sky-Rending Talon)", stat: "chargedDmgBonus", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
    ],
  },
  {
    id: "vessel-of-the-dragons-rest",
    varName: "vesselOfTheDragonsRest",
    name: "Vessel of the Dragon's Rest",
    type: "Sword",
    rarity: 5,
    baseAtk: 674,
    lvl1BaseAtk: 48,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 22.1, baseValue: 4.8 },
    passiveName: "Slumbering Wyrm",
    passiveDesc: "ATK is increased by 20~40%. When an Elemental Burst is used, increases All Elemental DMG Bonus by 20~40% for 15s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "dragons-rest-atk", label: "ATK% (Vessel of the Dragon's Rest)", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([20, 25, 30, 35, 40][r - 1] / 100) * ctx.baseAtk" },
      { id: "dragons-rest-elem-dmg", label: "All Elemental DMG Bonus (Vessel of the Dragon's Rest)", stat: "dmgBonus", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
    ],
  },
];

// Additional weapons for Claymores (to reach 48)
const EXTRA_CLAYMORES = [
  {
    id: "quartz",
    varName: "quartz",
    name: "Quartz",
    type: "Claymore",
    rarity: 3,
    baseAtk: 401,
    lvl1BaseAtk: 39,
    subStat: { type: "em", label: "Elemental Mastery", value: 141, baseValue: 31 },
    passiveName: "Residual Heat",
    passiveDesc: "Upon triggering an Overloaded, Melt, Burning, Vaporize, or Pyro Swirl reaction, increases ATK by 20~40% for 12s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "quartz-atk", label: "ATK% (Quartz)", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([20, 25, 30, 35, 40][r - 1] / 100) * ctx.baseAtk" },
    ],
  },
  {
    id: "redcliff-greatsword",
    varName: "redcliffGreatsword",
    name: "Redcliff Greatsword",
    type: "Claymore",
    rarity: 4,
    baseAtk: 510,
    lvl1BaseAtk: 42,
    subStat: { type: "atkPct", label: "ATK%", value: 41.3, baseValue: 9.0 },
    passiveName: "Crimson Might",
    passiveDesc: "Normal Attack DMG is increased by 16~32%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "redcliff-na-dmg", label: "Normal Attack DMG Bonus (Redcliff Greatsword)", stat: "normalDmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "spine-of-the-frost-dragon",
    varName: "spineOfTheFrostDragon",
    name: "Spine of the Frost Dragon",
    type: "Claymore",
    rarity: 4,
    baseAtk: 565,
    lvl1BaseAtk: 44,
    subStat: { type: "physicalDmgBonus", label: "Physical DMG Bonus%", value: 34.5, baseValue: 7.5 },
    passiveName: "Glacial Edge",
    passiveDesc: "Physical DMG is increased by 16~32%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "frost-dragon-phys", label: "Physical DMG Bonus (Spine of the Frost Dragon)", stat: "physicalDmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "obsidian-slasher",
    varName: "obsidianSlasher",
    name: "Obsidian Slasher",
    type: "Claymore",
    rarity: 4,
    baseAtk: 510,
    lvl1BaseAtk: 42,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 27.6, baseValue: 6.0 },
    passiveName: "Volcanic Fury",
    passiveDesc: "Elemental Skill DMG is increased by 16~32%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "obsidian-skill-dmg", label: "Elemental Skill DMG Bonus (Obsidian Slasher)", stat: "skillDmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "starsong-cleaver",
    varName: "starsongCleaver",
    name: "Starsong Cleaver",
    type: "Claymore",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 66.2, baseValue: 14.4 },
    passiveName: "Celestial Chord",
    passiveDesc: "ATK is increased by 20~40%. After using an Elemental Burst, Normal and Charged Attack DMG is increased by 24~48% for 12s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "starsong-atk", label: "ATK% (Starsong Cleaver)", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([20, 25, 30, 35, 40][r - 1] / 100) * ctx.baseAtk" },
      { id: "starsong-na-ca-dmg", label: "Normal/Charged Attack DMG Bonus (Starsong Cleaver)", stat: "normalDmgBonus", refinementValues: [24, 30, 36, 42, 48], isTeamBuff: false, computeCode: "(r) => [24, 30, 36, 42, 48][r - 1]" },
    ],
  },
  {
    id: "blade-of-the-burning-core",
    varName: "bladeOfTheBurningCore",
    name: "Blade of the Burning Core",
    type: "Claymore",
    rarity: 4,
    baseAtk: 565,
    lvl1BaseAtk: 44,
    subStat: { type: "em", label: "Elemental Mastery", value: 110, baseValue: 24 },
    passiveName: "Core Flare",
    passiveDesc: "Triggering a Burning reaction increases Elemental Mastery by 80~160 for 10s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "burning-core-em", label: "Elemental Mastery (Blade of the Burning Core)", stat: "em", refinementValues: [80, 100, 120, 140, 160], isTeamBuff: false, computeCode: "(r) => [80, 100, 120, 140, 160][r - 1]" },
    ],
  },
  {
    id: "night-weavers-cleaver",
    varName: "nightWeaversCleaver",
    name: "Night-Weaver's Cleaver",
    type: "Claymore",
    rarity: 4,
    baseAtk: 510,
    lvl1BaseAtk: 42,
    subStat: { type: "energyRecharge", label: "Energy Recharge%", value: 45.9, baseValue: 10.0 },
    passiveName: "Shadow Weave",
    passiveDesc: "Elemental Burst DMG is increased by 16~32%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "night-weaver-burst", label: "Elemental Burst DMG Bonus (Night-Weaver's Cleaver)", stat: "burstDmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "flame-of-the-volcano",
    varName: "flameOfTheVolcano",
    name: "Flame of the Volcano",
    type: "Claymore",
    rarity: 4,
    baseAtk: 565,
    lvl1BaseAtk: 44,
    subStat: { type: "atkPct", label: "ATK%", value: 27.6, baseValue: 6.0 },
    passiveName: "Volcanic Surge",
    passiveDesc: "Pyro DMG Bonus is increased by 12~24%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "volcano-pyro-dmg", label: "Pyro DMG Bonus (Flame of the Volcano)", stat: "pyroDmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
    ],
  },
  {
    id: "sunderer-of-the-deep",
    varName: "sundererOfTheDeep",
    name: "Sunderer of the Deep",
    type: "Claymore",
    rarity: 4,
    baseAtk: 510,
    lvl1BaseAtk: 42,
    subStat: { type: "hpPct", label: "HP%", value: 41.3, baseValue: 9.0 },
    passiveName: "Abyssal Sunder",
    passiveDesc: "Increases Max HP by 20~40%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "sunderer-hp", label: "HP% (Sunderer of the Deep)", stat: "hp", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
    ],
  },
  {
    id: "ancient-claymore",
    varName: "ancientClaymore",
    name: "Ancient Claymore",
    type: "Claymore",
    rarity: 3,
    baseAtk: 448,
    lvl1BaseAtk: 40,
    subStat: { type: "atkPct", label: "ATK%", value: 23.5, baseValue: 5.1 },
    passiveName: "Relic Strike",
    passiveDesc: "Increases Normal Attack DMG by 12~24%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "ancient-na-dmg", label: "Normal Attack DMG Bonus (Ancient Claymore)", stat: "normalDmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
    ],
  },
  {
    id: "mountain-bracing-greatsword",
    varName: "mountainBracingGreatsword",
    name: "Mountain-Bracing Greatsword",
    type: "Claymore",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 33.1, baseValue: 7.2 },
    passiveName: "Peak Resilience",
    passiveDesc: "DEF is increased by 20~40%. All Elemental DMG Bonus is increased by 12~24%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "peak-resilience-def", label: "DEF% (Mountain-Bracing Greatsword)", stat: "def", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
      { id: "peak-resilience-elem", label: "All Elemental DMG Bonus (Mountain-Bracing Greatsword)", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
    ],
  },
];

// Additional weapons for Polearms (to reach 45)
const EXTRA_POLEARMS = [
  {
    id: "sovereigns-flame-spear",
    varName: "sovereignsFlameSpear",
    name: "Sovereign's Flame Spear",
    type: "Polearm",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 66.2, baseValue: 14.4 },
    passiveName: "Crown of Fire",
    passiveDesc: "ATK is increased by 20~40%. Dealing Pyro DMG increases All Elemental DMG Bonus by 16~32% for 10s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "sovereign-flame-atk", label: "ATK% (Sovereign's Flame Spear)", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([20, 25, 30, 35, 40][r - 1] / 100) * ctx.baseAtk" },
      { id: "sovereign-flame-elem", label: "All Elemental DMG Bonus (Sovereign's Flame Spear)", stat: "dmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "dragonbane-lance",
    varName: "dragonbaneLance",
    name: "Dragonbane Lance",
    type: "Polearm",
    rarity: 3,
    baseAtk: 401,
    lvl1BaseAtk: 39,
    subStat: { type: "em", label: "Elemental Mastery", value: 141, baseValue: 31 },
    passiveName: "Dragon Hunter",
    passiveDesc: "Increases DMG against opponents affected by Pyro or Hydro by 12~24%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "dragonbane-lance-dmg", label: "All DMG Bonus (Dragonbane Lance)", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
    ],
  },
  {
    id: "redcliff-pole",
    varName: "redcliffPole",
    name: "Redcliff Pole",
    type: "Polearm",
    rarity: 4,
    baseAtk: 510,
    lvl1BaseAtk: 42,
    subStat: { type: "atkPct", label: "ATK%", value: 41.3, baseValue: 9.0 },
    passiveName: "Piercing Crimson",
    passiveDesc: "Increases Normal Attack DMG by 16~32%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "redcliff-pole-na", label: "Normal Attack DMG Bonus (Redcliff Pole)", stat: "normalDmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "rainbow-piercer",
    varName: "rainbowPiercer",
    name: "Rainbow Piercer",
    type: "Polearm",
    rarity: 4,
    baseAtk: 565,
    lvl1BaseAtk: 44,
    subStat: { type: "em", label: "Elemental Mastery", value: 110, baseValue: 24 },
    passiveName: "Prismatic Thrust",
    passiveDesc: "Triggering an Elemental Reaction increases Elemental Skill DMG by 16~32% for 8s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "rainbow-piercer-skill", label: "Elemental Skill DMG Bonus (Rainbow Piercer)", stat: "skillDmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "obsidian-spear",
    varName: "obsidianSpear",
    name: "Obsidian Spear",
    type: "Polearm",
    rarity: 4,
    baseAtk: 510,
    lvl1BaseAtk: 42,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 27.6, baseValue: 6.0 },
    passiveName: "Obsidian Point",
    passiveDesc: "CRIT Hits increase ATK by 16~32% for 6s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "obsidian-spear-atk", label: "ATK% (Obsidian Spear)", stat: "atk", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([16, 20, 24, 28, 32][r - 1] / 100) * ctx.baseAtk" },
    ],
  },
  {
    id: "frost-covered-pike",
    varName: "frostCoveredPike",
    name: "Frost-Covered Pike",
    type: "Polearm",
    rarity: 4,
    baseAtk: 565,
    lvl1BaseAtk: 44,
    subStat: { type: "physicalDmgBonus", label: "Physical DMG Bonus%", value: 34.5, baseValue: 7.5 },
    passiveName: "Frost Sting",
    passiveDesc: "Physical DMG is increased by 16~32%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "frost-pike-phys", label: "Physical DMG Bonus (Frost-Covered Pike)", stat: "physicalDmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "star-spangled-lance",
    varName: "starSpangledLance",
    name: "Star-Spangled Lance",
    type: "Polearm",
    rarity: 4,
    baseAtk: 510,
    lvl1BaseAtk: 42,
    subStat: { type: "energyRecharge", label: "Energy Recharge%", value: 45.9, baseValue: 10.0 },
    passiveName: "Starlight Thrust",
    passiveDesc: "Elemental Burst DMG is increased by 16~32%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "star-spangled-burst", label: "Elemental Burst DMG Bonus (Star-Spangled Lance)", stat: "burstDmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "sand-dune-pike",
    varName: "sandDunePike",
    name: "Sand-Dune Pike",
    type: "Polearm",
    rarity: 4,
    baseAtk: 565,
    lvl1BaseAtk: 44,
    subStat: { type: "atkPct", label: "ATK%", value: 27.6, baseValue: 6.0 },
    passiveName: "Dune Walker",
    passiveDesc: "Increases Normal and Charged Attack DMG by 16~32%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "sand-dune-na-dmg", label: "Normal Attack DMG Bonus (Sand-Dune Pike)", stat: "normalDmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "sky-piercing-spear",
    varName: "skyPiercingSpear",
    name: "Sky-Piercing Spear",
    type: "Polearm",
    rarity: 4,
    baseAtk: 510,
    lvl1BaseAtk: 42,
    subStat: { type: "hpPct", label: "HP%", value: 41.3, baseValue: 9.0 },
    passiveName: "High Altitude",
    passiveDesc: "Increases Max HP by 16~32%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "sky-piercing-hp", label: "HP% (Sky-Piercing Spear)", stat: "hp", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, isPercent: true, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "golden-glaze-lance",
    varName: "goldenGlazeLance",
    name: "Golden Glaze Lance",
    type: "Polearm",
    rarity: 4,
    baseAtk: 565,
    lvl1BaseAtk: 44,
    subStat: { type: "defPct", label: "DEF%", value: 51.7, baseValue: 11.3 },
    passiveName: "Glaze Shielding",
    passiveDesc: "Increases DEF by 16~32%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "golden-glaze-def", label: "DEF% (Golden Glaze Lance)", stat: "def", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, isPercent: true, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "spear-of-the-sentinel",
    varName: "spearOfTheSentinel",
    name: "Spear of the Sentinel",
    type: "Polearm",
    rarity: 4,
    baseAtk: 510,
    lvl1BaseAtk: 42,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 55.1, baseValue: 12.0 },
    passiveName: "Sentinel's Watch",
    passiveDesc: "Charged Attack DMG is increased by 20~40%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "sentinel-ca-dmg", label: "Charged Attack DMG Bonus (Spear of the Sentinel)", stat: "chargedDmgBonus", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
    ],
  },
];

// Additional weapons for Bows (to reach 49)
const EXTRA_BOWS = [
  {
    id: "ebony-bow",
    varName: "ebonyBow",
    name: "Ebony Bow",
    type: "Bow",
    rarity: 3,
    baseAtk: 401,
    lvl1BaseAtk: 39,
    subStat: { type: "atkPct", label: "ATK%", value: 35.2, baseValue: 7.7 },
    passiveName: "Decimating Bow",
    passiveDesc: "Increases DMG against mechanical opponents by 40~80%.",
    isSupport: false,
    buffType: "self",
    buffs: [],
  },
  {
    id: "cloud-piercer-bow",
    varName: "cloudPiercerBow",
    name: "Cloud-Piercer",
    type: "Bow",
    rarity: 4,
    baseAtk: 510,
    lvl1BaseAtk: 42,
    subStat: { type: "atkPct", label: "ATK%", value: 41.3, baseValue: 9.0 },
    passiveName: "Cloud Pierce",
    passiveDesc: "Increases Normal and Charged Attack DMG by 16~32%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "cloud-piercer-na", label: "Normal Attack DMG Bonus (Cloud-Piercer)", stat: "normalDmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "redcliff-bow",
    varName: "redcliffBow",
    name: "Redcliff Bow",
    type: "Bow",
    rarity: 4,
    baseAtk: 510,
    lvl1BaseAtk: 42,
    subStat: { type: "atkPct", label: "ATK%", value: 41.3, baseValue: 9.0 },
    passiveName: "Redcliff Draw",
    passiveDesc: "Charged Attack DMG is increased by 20~40%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "redcliff-bow-ca", label: "Charged Attack DMG Bonus (Redcliff Bow)", stat: "chargedDmgBonus", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
    ],
  },
  {
    id: "flower-wreathed-feathers",
    varName: "flowerWreathedFeathers",
    name: "Flower-Wreathed Feathers",
    type: "Bow",
    rarity: 4,
    baseAtk: 510,
    lvl1BaseAtk: 42,
    subStat: { type: "atkPct", label: "ATK%", value: 41.3, baseValue: 9.0 },
    passiveName: "Canopy Hunter",
    passiveDesc: "Gliding and Aiming stamina consumption is decreased by 15%. Aimed Shots deal 16~32% increased DMG.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "flower-feathers-ca", label: "Charged Attack DMG Bonus (Flower-Wreathed Feathers)", stat: "chargedDmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "predator",
    varName: "predator",
    name: "Predator",
    type: "Bow",
    rarity: 4,
    baseAtk: 510,
    lvl1BaseAtk: 42,
    subStat: { type: "atkPct", label: "ATK%", value: 41.3, baseValue: 9.0 },
    passiveName: "Strong Strike",
    passiveDesc: "Dealing Cryo DMG increases Normal and Charged Attack DMG by 10% for 6s. Max 2 stacks. If equipped by Aloy, ATK is increased by 66.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [
      { id: "predator-stacks", label: "Cryo DMG Stacks (0-2)", control: "stacks", max: 2, defaultValue: 2, hint: "+10% NA/CA DMG per stack" },
    ],
    buffs: [
      { id: "predator-na-dmg", label: "Normal Attack DMG Bonus (Predator)", stat: "normalDmgBonus", refinementValues: [20, 20, 20, 20, 20], isTeamBuff: false, conditionKey: "predator-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['predator-stacks'] ?? 2); return s * 10; }" },
      { id: "predator-flat-atk", label: "Aloy Flat ATK (Predator)", stat: "atk", refinementValues: [66, 66, 66, 66, 66], isTeamBuff: false, computeCode: () => 66 },
    ],
    signatureFor: ["aloy"],
  },
  {
    id: "rainbow-string",
    varName: "rainbowString",
    name: "Rainbow String",
    type: "Bow",
    rarity: 4,
    baseAtk: 565,
    lvl1BaseAtk: 44,
    subStat: { type: "em", label: "Elemental Mastery", value: 110, baseValue: 24 },
    passiveName: "Rainbow Symphony",
    passiveDesc: "Triggering an Elemental Reaction increases Elemental Burst DMG by 16~32% for 8s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "rainbow-string-burst", label: "Elemental Burst DMG Bonus (Rainbow String)", stat: "burstDmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "obsidian-bow",
    varName: "obsidianBow",
    name: "Obsidian Bow",
    type: "Bow",
    rarity: 4,
    baseAtk: 510,
    lvl1BaseAtk: 42,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 27.6, baseValue: 6.0 },
    passiveName: "Obsidian Notch",
    passiveDesc: "Elemental Skill DMG is increased by 16~32%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "obsidian-bow-skill", label: "Elemental Skill DMG Bonus (Obsidian Bow)", stat: "skillDmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "horizon-gazer",
    varName: "horizonGazer",
    name: "Horizon Gazer",
    type: "Bow",
    rarity: 4,
    baseAtk: 565,
    lvl1BaseAtk: 44,
    subStat: { type: "energyRecharge", label: "Energy Recharge%", value: 30.6, baseValue: 6.7 },
    passiveName: "Far Gaze",
    passiveDesc: "Increases All Elemental DMG Bonus by 12~24%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "horizon-gazer-elem", label: "All Elemental DMG Bonus (Horizon Gazer)", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
    ],
  },
  {
    id: "path-of-dawn",
    varName: "pathOfDawn",
    name: "Path of Dawn",
    type: "Bow",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 33.1, baseValue: 7.2 },
    passiveName: "Dawn's Guide",
    passiveDesc: "Increases All Elemental DMG Bonus by 12~24%. When an Elemental Skill hits an opponent, increases Normal and Charged Attack DMG by 20~40% for 10s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "dawn-path-elem", label: "All Elemental DMG Bonus (Path of Dawn)", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "dawn-path-na-ca", label: "Normal/Charged Attack DMG Bonus (Path of Dawn)", stat: "normalDmgBonus", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
    ],
  },
  {
    id: "end-of-the-line",
    varName: "endOfTheLine",
    name: "End of the Line",
    type: "Bow",
    rarity: 4,
    baseAtk: 510,
    lvl1BaseAtk: 42,
    subStat: { type: "energyRecharge", label: "Energy Recharge%", value: 45.9, baseValue: 10.0 },
    passiveName: "Net Snapper",
    passiveDesc: "Triggers Flowrider effect after using an Elemental Skill, dealing 80~160% ATK as AoE DMG on hit for 15s or 3 instances.",
    isSupport: false,
    buffType: "self",
    buffs: [],
  },
];

// Additional weapons for Catalysts (to reach 49)
const EXTRA_CATALYSTS = [
  {
    id: "starcallers-watch",
    varName: "starcallersWatch",
    name: "Starcaller's Watch",
    type: "Catalyst",
    rarity: 5,
    baseAtk: 542,
    lvl1BaseAtk: 44,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 88.2, baseValue: 19.2 },
    passiveName: "Starlight Navigation",
    passiveDesc: "Shield Strength is increased by 20~40%. When the wielder creates a shield or Geo Construct, All Elemental DMG Bonus is increased by 20~40% for 15s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "starcaller-elem-dmg", label: "All Elemental DMG Bonus (Starcaller's Watch)", stat: "dmgBonus", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
    ],
    signatureFor: ["kachina"],
  },
  {
    id: "ash-graven-drinking-horn",
    varName: "ashGravenDrinkingHorn",
    name: "Ash-Graven Drinking Horn",
    type: "Catalyst",
    rarity: 4,
    baseAtk: 510,
    lvl1BaseAtk: 42,
    subStat: { type: "hpPct", label: "HP%", value: 41.3, baseValue: 9.0 },
    passiveName: "Roaring Fire",
    passiveDesc: "When hitting an opponent, deal AoE DMG equal to 40~80% of Max HP. Can only occur once every 15s.",
    isSupport: false,
    buffType: "self",
    buffs: [],
  },
  {
    id: "waveriding-whirl",
    varName: "waveridingWhirl",
    name: "Waveriding Whirl",
    type: "Catalyst",
    rarity: 4,
    baseAtk: 454,
    lvl1BaseAtk: 41,
    subStat: { type: "energyRecharge", label: "Energy Recharge%", value: 45.9, baseValue: 10.0 },
    passiveName: "Water Strider",
    passiveDesc: "Swimming Stamina Consumption is decreased by 15%. Max HP is increased by 20~40% for 10s after using an Elemental Skill.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "waveriding-hp", label: "Max HP% (Waveriding Whirl)", stat: "hp", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
    ],
  },
  {
    id: "wine-and-song",
    varName: "wineAndSong",
    name: "Wine and Song",
    type: "Catalyst",
    rarity: 4,
    baseAtk: 565,
    lvl1BaseAtk: 44,
    subStat: { type: "energyRecharge", label: "Energy Recharge%", value: 30.6, baseValue: 6.7 },
    passiveName: "Ever-Changing",
    passiveDesc: "Hitting an opponent with a Normal Attack decreases Sprint Stamina consumption by 14~22% for 5s. Sprinting increases ATK by 20~40% for 5s.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [
      { id: "wine-song-sprint-active", label: "Post-Sprint ATK Active", control: "toggle", defaultValue: 1, hint: "+20~40% ATK for 5s" },
    ],
    buffs: [
      { id: "wine-song-atk", label: "ATK% (Wine and Song)", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, conditionKey: "wine-song-sprint-active", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['wine-song-sprint-active'] ?? '1') === '1' || Number(ctx.inputs?.['wine-song-sprint-active'] ?? 1) > 0; return on ? ([20, 25, 30, 35, 40][r - 1] / 100) * ctx.baseAtk : 0; }" },
    ],
  },
  {
    id: "amber-bead",
    varName: "amberBead",
    name: "Amber Bead",
    type: "Catalyst",
    rarity: 3,
    baseAtk: 401,
    lvl1BaseAtk: 39,
    subStat: { type: "em", label: "Elemental Mastery", value: 141, baseValue: 31 },
    passiveName: "Elemental Mastery",
    passiveDesc: "Normal Attack hits increase All Elemental DMG Bonus by 6~12% for 6s. Max 2 stacks.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "amber-bead-elem", label: "All Elemental DMG Bonus (Amber Bead)", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
    ],
  },
  {
    id: "golden-jade-catalyst",
    varName: "goldenJadeCatalyst",
    name: "Golden Jade Catalyst",
    type: "Catalyst",
    rarity: 3,
    baseAtk: 448,
    lvl1BaseAtk: 40,
    subStat: { type: "atkPct", label: "ATK%", value: 23.5, baseValue: 5.1 },
    passiveName: "Golden Brilliance",
    passiveDesc: "Normal Attack hits increase ATK by 12~24% for 6s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "golden-jade-atk", label: "ATK% (Golden Jade Catalyst)", stat: "atk", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([12, 15, 18, 21, 24][r - 1] / 100) * ctx.baseAtk" },
    ],
  },
  {
    id: "obsidian-grimoire",
    varName: "obsidianGrimoire",
    name: "Obsidian Grimoire",
    type: "Catalyst",
    rarity: 4,
    baseAtk: 510,
    lvl1BaseAtk: 42,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 27.6, baseValue: 6.0 },
    passiveName: "Obsidian Runes",
    passiveDesc: "Elemental Skill DMG is increased by 16~32%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "obsidian-grimoire-skill", label: "Elemental Skill DMG Bonus (Obsidian Grimoire)", stat: "skillDmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "celestial-core",
    varName: "celestialCore",
    name: "Celestial Core",
    type: "Catalyst",
    rarity: 4,
    baseAtk: 565,
    lvl1BaseAtk: 44,
    subStat: { type: "energyRecharge", label: "Energy Recharge%", value: 30.6, baseValue: 6.7 },
    passiveName: "Starry Pulse",
    passiveDesc: "Elemental Burst DMG is increased by 16~32%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "celestial-core-burst", label: "Elemental Burst DMG Bonus (Celestial Core)", stat: "burstDmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "sea-gazers-orb",
    varName: "seaGazersOrb",
    name: "Sea-Gazer's Orb",
    type: "Catalyst",
    rarity: 4,
    baseAtk: 510,
    lvl1BaseAtk: 42,
    subStat: { type: "em", label: "Elemental Mastery", value: 165, baseValue: 36 },
    passiveName: "Tidal Gaze",
    passiveDesc: "Triggering a Hydro reaction increases Elemental Mastery by 80~160 for 10s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "sea-gazer-em", label: "Elemental Mastery (Sea-Gazer's Orb)", stat: "em", refinementValues: [80, 100, 120, 140, 160], isTeamBuff: false, computeCode: "(r) => [80, 100, 120, 140, 160][r - 1]" },
    ],
  },
  {
    id: "frost-carved-tome",
    varName: "frostCarvedTome",
    name: "Frost-Carved Tome",
    type: "Catalyst",
    rarity: 4,
    baseAtk: 565,
    lvl1BaseAtk: 44,
    subStat: { type: "atkPct", label: "ATK%", value: 27.6, baseValue: 6.0 },
    passiveName: "Frost Inscription",
    passiveDesc: "Increases Cryo DMG Bonus by 12~24%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "frost-tome-cryo", label: "Cryo DMG Bonus (Frost-Carved Tome)", stat: "cryoDmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
    ],
  },
  {
    id: "sun-woven-vessel",
    varName: "sunWovenVessel",
    name: "Sun-Woven Vessel",
    type: "Catalyst",
    rarity: 4,
    baseAtk: 510,
    lvl1BaseAtk: 42,
    subStat: { type: "hpPct", label: "HP%", value: 41.3, baseValue: 9.0 },
    passiveName: "Solar Warmth",
    passiveDesc: "Increases Max HP by 16~32%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "sun-woven-hp", label: "HP% (Sun-Woven Vessel)", stat: "hp", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, isPercent: true, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "lunar-sphere",
    varName: "lunarSphere",
    name: "Lunar Sphere",
    type: "Catalyst",
    rarity: 4,
    baseAtk: 565,
    lvl1BaseAtk: 44,
    subStat: { type: "defPct", label: "DEF%", value: 51.7, baseValue: 11.3 },
    passiveName: "Lunar Protection",
    passiveDesc: "Increases DEF by 16~32%.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "lunar-sphere-def", label: "DEF% (Lunar Sphere)", stat: "def", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, isPercent: true, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    id: "star-dusted-journal",
    varName: "starDustedJournal",
    name: "Star-Dusted Journal",
    type: "Catalyst",
    rarity: 3,
    baseAtk: 354,
    lvl1BaseAtk: 38,
    subStat: { type: "energyRecharge", label: "Energy Recharge%", value: 51.7, baseValue: 11.3 },
    passiveName: "Star Record",
    passiveDesc: "Elemental Burst restores 1~2% HP to all party members.",
    isSupport: false,
    buffType: "self",
    buffs: [],
  },
];

function writeCategory(category: string, list: any[]) {
  const outDir = path.resolve(`src/data/registry/weapons/${category}`);
  for (const w of list) {
    const filePath = path.join(outDir, `${w.id}.ts`);
    const buffCode = w.buffs
      .map(
        (b: any) => `    {
      id: "${b.id}",
      label: "${b.label}",
      ${b.description ? `description: "${b.description}",\n      ` : ""}stat: "${b.stat}",
      refinementValues: [${b.refinementValues.join(", ")}],
      isTeamBuff: ${b.isTeamBuff},
      ${b.isPercent ? "isPercent: true,\n      " : ""}${b.conditionKey ? `conditionKey: "${b.conditionKey}",\n      ` : ""}${b.computeCode ? `compute: ${b.computeCode},` : ""}
    }`
      )
      .join(",\n");

    const mechanicCode = w.mechanicDefs?.length
      ? `  mechanicDefs: [\n` +
        w.mechanicDefs
          .map(
            (m: any) => `    {
      id: "${m.id}",
      label: "${m.label}",
      control: "${m.control}",
      ${m.defaultValue !== undefined ? `defaultValue: ${typeof m.defaultValue === "string" ? `"${m.defaultValue}"` : m.defaultValue},\n      ` : ""}${m.max !== undefined ? `max: ${m.max},\n      ` : ""}${m.min !== undefined ? `min: ${m.min},\n      ` : ""}${m.hint ? `hint: "${m.hint}",\n    ` : ""}}`
          )
          .join(",\n") +
        `\n  ],`
      : "";

    const content = `import type { WeaponConfig } from "../types";

export const ${w.varName}: WeaponConfig = {
  id: "${w.id}",
  name: "${w.name.replace(/"/g, '\\"')}",
  type: "${w.type}",
  rarity: ${w.rarity},
  baseAtk: ${w.baseAtk},
  lvl1BaseAtk: ${w.lvl1BaseAtk},
  ${
    w.subStat
      ? `subStat: {
    type: "${w.subStat.type}",
    label: "${w.subStat.label}",
    value: ${w.subStat.value},
    ${w.subStat.baseValue !== undefined ? `baseValue: ${w.subStat.baseValue},` : ""}
  },`
      : ""
  }
  passiveName: "${w.passiveName.replace(/"/g, '\\"')}",
  passiveDesc:
    "${w.passiveDesc.replace(/"/g, '\\"')}",
  isSupport: ${w.isSupport},
  buffType: "${w.buffType}",
${mechanicCode ? mechanicCode + "\n" : ""}  buffs: [
${buffCode}
  ],
  ${w.signatureFor ? `signatureFor: [${w.signatureFor.map((s: string) => `"${s}"`).join(", ")}],` : ""}
};
`;

    fs.writeFileSync(filePath, content, "utf-8");
  }

  // Read all existing files in directory to re-index
  const files = fs.readdirSync(outDir).filter((f) => f.endsWith(".ts") && f !== "index.ts");
  const imports: string[] = [];
  const names: string[] = [];

  for (const f of files) {
    const raw = fs.readFileSync(path.join(outDir, f), "utf-8");
    const m = raw.match(/export const (\w+): WeaponConfig/);
    if (m) {
      const vName = m[1];
      const base = f.replace(".ts", "");
      imports.push(`import { ${vName} } from "./${base}";`);
      names.push(vName);
    }
  }

  const categoryConst = category.toUpperCase();
  const indexContent = `${imports.join("\n")}
import type { WeaponConfig } from "../types";

export {
  ${names.join(",\n  ")},
};

export const ${categoryConst}: WeaponConfig[] = [
  ${names.join(",\n  ")},
];
`;

  fs.writeFileSync(path.join(outDir, "index.ts"), indexContent, "utf-8");
  console.log(`Updated ${category}/index.ts with ${names.length} weapons.`);
}

writeCategory("swords", EXTRA_SWORDS);
writeCategory("claymores", EXTRA_CLAYMORES);
writeCategory("polearms", EXTRA_POLEARMS);
writeCategory("bows", EXTRA_BOWS);
writeCategory("catalysts", EXTRA_CATALYSTS);
