import fs from "fs";
import path from "path";

// Helper to convert weapon name to slug ID and camelCase variable name
export function toSlug(name: string): string {
  return name
    .replace(/^["']|["']$/g, "") // Remove wrapping quotes
    .toLowerCase()
    .replace(/['’]/g, "") // Remove apostrophes
    .replace(/[^a-z0-9]+/g, "-") // Replace non-alphanumeric with hyphen
    .replace(/^-+|-+$/g, ""); // Trim hyphens
}

export function toVarName(name: string): string {
  const slug = toSlug(name);
  return slug.replace(/-([a-z0-9])/g, (_, g) => g.toUpperCase());
}

export interface WeaponDef {
  name: string;
  type: "Sword" | "Claymore" | "Polearm" | "Bow" | "Catalyst";
  rarity: 1 | 2 | 3 | 4 | 5;
  baseAtk: number;
  lvl1BaseAtk: number;
  subStat?: {
    type: string;
    label: string;
    value: number;
    baseValue?: number;
  };
  passiveName: string;
  passiveDesc: string;
  isSupport: boolean;
  buffType: "team" | "self" | "both";
  buffs: any[];
  mechanicDefs?: any[];
  signatureFor?: string[];
}

// Complete master dictionary of all 246 weapons from user's list
export const ALL_246_WEAPONS: WeaponDef[] = [
  // ==========================================
  // 5-STAR WEAPONS (73)
  // ==========================================
  // Catalysts 5★
  {
    name: "A Teaspoon of Transcendence",
    type: "Catalyst",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 66.2, baseValue: 14.4 },
    passiveName: "Tea-Time Melody",
    passiveDesc: "Increases All Elemental DMG Bonus by 12~24%. After using an Elemental Skill, ATK is increased by 16~32% for 12s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "teaspoon-elem-dmg", label: "All Elemental DMG Bonus", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "teaspoon-atk", label: "ATK%", stat: "atk", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([16, 20, 24, 28, 32][r - 1] / 100) * ctx.baseAtk" },
    ],
  },
  {
    name: "A Thousand Blazing Suns",
    type: "Claymore",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 33.1, baseValue: 7.2 },
    passiveName: "Scorching Reverence",
    passiveDesc: "Increases CRIT DMG by 20~40%. When in Nightsoul's Blessing or triggering a Nightsoul Burst, increases ATK by 28~56% for 6s.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "blazing-suns-active", label: "Nightsoul Burst Triggered", control: "toggle", defaultValue: 1, hint: "+28~56% ATK for 6s" }],
    buffs: [
      { id: "blazing-suns-crit-dmg", label: "CRIT DMG%", stat: "critDmg", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
      { id: "blazing-suns-atk", label: "ATK%", stat: "atk", refinementValues: [28, 35, 42, 49, 56], isTeamBuff: false, isPercent: true, conditionKey: "blazing-suns-active", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['blazing-suns-active'] ?? '1') === '1' || Number(ctx.inputs?.['blazing-suns-active'] ?? 1) > 0; return on ? ([28, 35, 42, 49, 56][r - 1] / 100) * ctx.baseAtk : 0; }" },
    ],
    signatureFor: ["mavuika"],
  },
  {
    name: "A Thousand Floating Dreams",
    type: "Catalyst",
    rarity: 5,
    baseAtk: 542,
    lvl1BaseAtk: 44,
    subStat: { type: "em", label: "Elemental Mastery", value: 265, baseValue: 58 },
    passiveName: "A Thousand Nights' Dawnsong",
    passiveDesc: "Party members other than the equipping character will provide buffs: same element grants 32~64 EM; different element grants 10~26% DMG Bonus. Nearby party members gain 40~48 EM.",
    isSupport: true,
    buffType: "both",
    mechanicDefs: [
      { id: "floating-same-elem-count", label: "Same-Element Teammates (0-3)", control: "stacks", max: 3, defaultValue: 1, hint: "+32~64 EM per same-element teammate to wielder" },
      { id: "floating-diff-elem-count", label: "Different-Element Teammates (0-3)", control: "stacks", max: 3, defaultValue: 2, hint: "+10~26% DMG Bonus per diff-element teammate to wielder" },
    ],
    buffs: [
      { id: "floating-dreams-party-em", label: "Party EM (A Thousand Floating Dreams)", description: "Nearby party members gain +40~48 Elemental Mastery", stat: "em", refinementValues: [40, 42, 44, 46, 48], isTeamBuff: true, computeCode: "(r) => [40, 42, 44, 46, 48][r - 1]" },
      { id: "floating-dreams-self-em", label: "Self EM from Same-Element Teammates", stat: "em", refinementValues: [32, 40, 48, 56, 64], isTeamBuff: false, conditionKey: "floating-same-elem-count", computeCode: "(r, ctx) => { const count = Number(ctx.inputs?.['floating-same-elem-count'] ?? 1); const perStack = [32, 40, 48, 56, 64][r - 1]; return count * perStack; }" },
      { id: "floating-dreams-self-dmg", label: "Self Elemental DMG Bonus from Diff-Element Teammates", stat: "dmgBonus", refinementValues: [10, 14, 18, 22, 26], isTeamBuff: false, conditionKey: "floating-diff-elem-count", computeCode: "(r, ctx) => { const count = Number(ctx.inputs?.['floating-diff-elem-count'] ?? 2); const perStack = [10, 14, 18, 22, 26][r - 1]; return count * perStack; }" },
    ],
    signatureFor: ["nahida"],
  },
  {
    name: "Absolution",
    type: "Sword",
    rarity: 5,
    baseAtk: 674,
    lvl1BaseAtk: 48,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 44.1, baseValue: 9.6 },
    passiveName: "Climb the Flowing Shadows",
    passiveDesc: "CRIT DMG is increased by 20~40%. When the value of a Bond of Life increases, the wielder deals 16~32% increased DMG for 6s. Max 3 stacks.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "absolution-stacks", label: "Bond of Life Increase Stacks (0-3)", control: "stacks", max: 3, defaultValue: 3, hint: "+16~32% All DMG bonus per stack (up to +48~96%)" }],
    buffs: [
      { id: "absolution-crit-dmg", label: "CRIT DMG% (Absolution)", stat: "critDmg", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
      { id: "absolution-dmg-bonus", label: "All DMG Bonus (Absolution BoL Stacks)", stat: "dmgBonus", refinementValues: [48, 60, 72, 84, 96], isTeamBuff: false, conditionKey: "absolution-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['absolution-stacks'] ?? 3); return s * [16, 20, 24, 28, 32][r - 1]; }" },
    ],
    signatureFor: ["clorinde"],
  },
  {
    name: "Amos' Bow",
    type: "Bow",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "atkPct", label: "ATK%", value: 49.6, baseValue: 10.8 },
    passiveName: "Strong-Willed",
    passiveDesc: "Increases Normal and Charged Attack DMG by 12~24%. Normal and Charged Attack DMG increases by 8~16% for every 0.1s the arrow is in the air up to 5 times.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "amos-arrow-stacks", label: "Arrow Flight Time Stacks (0-5)", control: "stacks", max: 5, defaultValue: 5, hint: "+8~16% NA/CA DMG per 0.1s flight (up to +40~80%)" }],
    buffs: [
      { id: "amos-base-na-ca-dmg", label: "Normal/Charged Attack DMG Bonus (Amos Base)", stat: "normalDmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "amos-base-charged-dmg", label: "Charged Attack DMG Bonus (Amos Base)", stat: "chargedDmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "amos-flight-na-dmg", label: "Flight Time NA DMG Bonus (Amos' Bow)", stat: "normalDmgBonus", refinementValues: [40, 50, 60, 70, 80], isTeamBuff: false, conditionKey: "amos-arrow-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['amos-arrow-stacks'] ?? 5); return s * [8, 10, 12, 14, 16][r - 1]; }" },
      { id: "amos-flight-ca-dmg", label: "Flight Time CA DMG Bonus (Amos' Bow)", stat: "chargedDmgBonus", refinementValues: [40, 50, 60, 70, 80], isTeamBuff: false, conditionKey: "amos-arrow-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['amos-arrow-stacks'] ?? 5); return s * [8, 10, 12, 14, 16][r - 1]; }" },
    ],
    signatureFor: ["ganyu"],
  },
  {
    name: "Angelos' Heptades",
    type: "Sword",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 33.1, baseValue: 7.2 },
    passiveName: "Heptadic Chord",
    passiveDesc: "Increases All Elemental DMG Bonus by 12~24%. Normal and Charged Attacks dealing Elemental DMG grant +16~32% ATK for 10s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "angelos-elem-dmg", label: "All Elemental DMG Bonus", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "angelos-atk", label: "ATK%", stat: "atk", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([16, 20, 24, 28, 32][r - 1] / 100) * ctx.baseAtk" },
    ],
  },
  {
    name: "Aqua Simulacra",
    type: "Bow",
    rarity: 5,
    baseAtk: 542,
    lvl1BaseAtk: 44,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 88.2, baseValue: 19.2 },
    passiveName: "The Cleansing Form",
    passiveDesc: "HP is increased by 16~32%. When there are opponents nearby, the DMG dealt by the wielder is increased by 20~40%. This takes effect whether the character is on-field or off-field.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "aqua-nearby-opponents", label: "Opponents Nearby (Active DMG Buff)", control: "toggle", defaultValue: 1, hint: "+20~40% All DMG bonus" }],
    buffs: [
      { id: "aqua-hp", label: "HP% (Aqua Simulacra)", stat: "hp", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, isPercent: true, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
      { id: "aqua-dmg", label: "All DMG Bonus (Aqua Simulacra Nearby)", stat: "dmgBonus", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, conditionKey: "aqua-nearby-opponents", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['aqua-nearby-opponents'] ?? '1') === '1' || Number(ctx.inputs?.['aqua-nearby-opponents'] ?? 1) > 0; return on ? [20, 25, 30, 35, 40][r - 1] : 0; }" },
    ],
    signatureFor: ["yelan"],
  },
  {
    name: "Aquila Favonia",
    type: "Sword",
    rarity: 5,
    baseAtk: 674,
    lvl1BaseAtk: 48,
    subStat: { type: "physicalDmgBonus", label: "Physical DMG Bonus%", value: 41.3, baseValue: 9.0 },
    passiveName: "Falcon's Defiance",
    passiveDesc: "ATK is increased by 20~40%. Triggers on taking DMG: the soul of the Falcon of the West awakens, regenerating HP equal to 100~160% of ATK and dealing 200~320% of ATK as DMG to surrounding opponents.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "aquila-atk", label: "ATK% (Aquila Favonia)", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([20, 25, 30, 35, 40][r - 1] / 100) * ctx.baseAtk" },
    ],
    signatureFor: ["jean"],
  },
  {
    name: "Astral Vulture's Crimson Plumage",
    type: "Bow",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 66.2, baseValue: 14.4 },
    passiveName: "Soaring Eagle's Cry",
    passiveDesc: "Triggering a Swirl reaction grants 1 stack of Unity, increasing Aimed Shot and Plunging Attack DMG by 20~40% for 12s. Max 2 stacks. When in Nightsoul's Blessing, the wielder deals an additional 20~40% DMG.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [
      { id: "astral-unity-stacks", label: "Swirl Unity Stacks (0-2)", control: "stacks", max: 2, defaultValue: 2, hint: "+20~40% Aimed/Plunging DMG per stack" },
      { id: "astral-nightsoul-active", label: "In Nightsoul's Blessing", control: "toggle", defaultValue: 1, hint: "+20~40% All DMG bonus" },
    ],
    buffs: [
      { id: "astral-ca-dmg", label: "Charged Attack DMG Bonus (Astral Vulture)", stat: "chargedDmgBonus", refinementValues: [40, 50, 60, 70, 80], isTeamBuff: false, conditionKey: "astral-unity-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['astral-unity-stacks'] ?? 2); return s * [20, 25, 30, 35, 40][r - 1]; }" },
      { id: "astral-nightsoul-dmg", label: "All DMG Bonus (Astral Nightsoul)", stat: "dmgBonus", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, conditionKey: "astral-nightsoul-active", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['astral-nightsoul-active'] ?? '1') === '1' || Number(ctx.inputs?.['astral-nightsoul-active'] ?? 1) > 0; return on ? [20, 25, 30, 35, 40][r - 1] : 0; }" },
    ],
    signatureFor: ["chasca"],
  },
  {
    name: "Athame Artis",
    type: "Sword",
    rarity: 5,
    baseAtk: 674,
    lvl1BaseAtk: 48,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 44.1, baseValue: 9.6 },
    passiveName: "Ritual Cleaving",
    passiveDesc: "Increases Normal and Charged Attack DMG by 20~40%. When an Elemental Burst is used, increases ATK by 20~40% for 12s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "athame-na-ca-dmg", label: "Normal/Charged Attack DMG Bonus", stat: "normalDmgBonus", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
      { id: "athame-atk", label: "ATK%", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([20, 25, 30, 35, 40][r - 1] / 100) * ctx.baseAtk" },
    ],
  },
  {
    name: "Azurelight",
    type: "Sword",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 33.1, baseValue: 7.2 },
    passiveName: "Azure Brilliance",
    passiveDesc: "All Elemental DMG Bonus is increased by 12~24%. Elemental Skill hits increase CRIT DMG by 20~40% for 8s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "azurelight-elem-dmg", label: "All Elemental DMG Bonus", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "azurelight-crit-dmg", label: "CRIT DMG%", stat: "critDmg", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
    ],
  },
  {
    name: "Beacon of the Reed Sea",
    type: "Claymore",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 33.1, baseValue: 7.2 },
    passiveName: "Desert Watch",
    passiveDesc: "After an Elemental Skill hits an opponent, ATK is increased by 20~40% for 8s. After taking DMG, ATK is increased by 20~40% for 8s. When not protected by a shield, Max HP is increased by 32~64%.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [
      { id: "beacon-skill-hit", label: "Skill Hit Opponent (+20~40% ATK)", control: "toggle", defaultValue: 1, hint: "+20~40% ATK" },
      { id: "beacon-took-dmg", label: "Character Took DMG (+20~40% ATK)", control: "toggle", defaultValue: 1, hint: "+20~40% ATK" },
      { id: "beacon-unshielded", label: "Unshielded (+32~64% Max HP)", control: "toggle", defaultValue: 1, hint: "+32~64% Max HP" },
    ],
    buffs: [
      { id: "beacon-skill-atk", label: "ATK% from Skill Hit (Beacon)", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, conditionKey: "beacon-skill-hit", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['beacon-skill-hit'] ?? '1') === '1' || Number(ctx.inputs?.['beacon-skill-hit'] ?? 1) > 0; return on ? ([20, 25, 30, 35, 40][r - 1] / 100) * ctx.baseAtk : 0; }" },
      { id: "beacon-dmg-atk", label: "ATK% from Taking DMG (Beacon)", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, conditionKey: "beacon-took-dmg", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['beacon-took-dmg'] ?? '1') === '1' || Number(ctx.inputs?.['beacon-took-dmg'] ?? 1) > 0; return on ? ([20, 25, 30, 35, 40][r - 1] / 100) * ctx.baseAtk : 0; }" },
      { id: "beacon-hp", label: "Max HP% (Beacon Unshielded)", stat: "hp", refinementValues: [32, 40, 48, 56, 64], isTeamBuff: false, isPercent: true, conditionKey: "beacon-unshielded", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['beacon-unshielded'] ?? '1') === '1' || Number(ctx.inputs?.['beacon-unshielded'] ?? 1) > 0; return on ? [32, 40, 48, 56, 64][r - 1] : 0; }" },
    ],
    signatureFor: ["dehya"],
  },
  {
    name: "Bloodsoaked Ruins",
    type: "Claymore",
    rarity: 5,
    baseAtk: 674,
    lvl1BaseAtk: 48,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 44.1, baseValue: 9.6 },
    passiveName: "Ancient Ruin",
    passiveDesc: "ATK is increased by 20~40%. When defeating an opponent, All Elemental DMG Bonus is increased by 20~40% for 15s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "bloodsoaked-atk", label: "ATK%", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([20, 25, 30, 35, 40][r - 1] / 100) * ctx.baseAtk" },
      { id: "bloodsoaked-elem-dmg", label: "All Elemental DMG Bonus", stat: "dmgBonus", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
    ],
  },
  {
    name: "Calamity Queller",
    type: "Polearm",
    rarity: 5,
    baseAtk: 741,
    lvl1BaseAtk: 49,
    subStat: { type: "atkPct", label: "ATK%", value: 16.5, baseValue: 3.6 },
    passiveName: "Extinguishing Precept",
    passiveDesc: "Gain 12~24% All Elemental DMG Bonus. Obtain Consummation after using an Elemental Skill, causing ATK to increase by 3.2~6.4% per second. Max 6 stacks. When the character equipped with this weapon is not on the field, Consummation's ATK increase is doubled.",
    isSupport: true,
    buffType: "both",
    mechanicDefs: [
      { id: "calamity-stacks", label: "Consummation Stacks (0-6)", control: "stacks", max: 6, defaultValue: 6, hint: "+3.2~6.4% ATK per stack (up to 19.2~38.4%)" },
      { id: "calamity-off-field", label: "Wielder is Off-Field (2x ATK Buff)", control: "toggle", defaultValue: 1, hint: "Doubles ATK bonus from stacks (up to 38.4~76.8% ATK)" },
    ],
    buffs: [
      { id: "calamity-elem-dmg", label: "All Elemental DMG Bonus (Calamity Queller)", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "calamity-atk", label: "ATK% (Calamity Queller Consummation)", stat: "atk", refinementValues: [19.2, 24, 28.8, 33.6, 38.4], isTeamBuff: false, isPercent: true, conditionKey: "calamity-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['calamity-stacks'] ?? 6); const offField = (ctx.inputs?.['calamity-off-field'] ?? '1') === '1' || Number(ctx.inputs?.['calamity-off-field'] ?? 1) > 0; const mult = offField ? 2 : 1; const baseRatio = [0.032, 0.04, 0.048, 0.056, 0.064][r - 1]; return s * baseRatio * mult * ctx.baseAtk; }" },
    ],
    signatureFor: ["shenhe"],
  },
  {
    name: "Cashflow Supervision",
    type: "Catalyst",
    rarity: 5,
    baseAtk: 674,
    lvl1BaseAtk: 48,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 22.1, baseValue: 4.8 },
    passiveName: "Golden Blood-Tide",
    passiveDesc: "ATK is increased by 16~32%. When current HP increases or decreases, Normal Attack DMG is increased by 16~32% and Charged Attack DMG is increased by 14~28% for 4s. Max 3 stacks. At 3 stacks, ATK SPD is increased by 8~16%.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "cashflow-stacks", label: "HP Change Stacks (0-3)", control: "stacks", max: 3, defaultValue: 3, hint: "+16~32% NA DMG and +14~28% CA DMG per stack (up to +48~96% NA, +42~84% CA)" }],
    buffs: [
      { id: "cashflow-atk", label: "ATK% (Cashflow Supervision)", stat: "atk", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([16, 20, 24, 28, 32][r - 1] / 100) * ctx.baseAtk" },
      { id: "cashflow-na-dmg", label: "Normal Attack DMG Bonus (Cashflow Supervision)", stat: "normalDmgBonus", refinementValues: [48, 60, 72, 84, 96], isTeamBuff: false, conditionKey: "cashflow-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['cashflow-stacks'] ?? 3); return s * [16, 20, 24, 28, 32][r - 1]; }" },
      { id: "cashflow-ca-dmg", label: "Charged Attack DMG Bonus (Cashflow Supervision)", stat: "chargedDmgBonus", refinementValues: [42, 52.5, 63, 73.5, 84], isTeamBuff: false, conditionKey: "cashflow-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['cashflow-stacks'] ?? 3); return s * [14, 17.5, 21, 24.5, 28][r - 1]; }" },
    ],
    signatureFor: ["wriothesley"],
  },
  {
    name: "Crane's Echoing Call",
    type: "Catalyst",
    rarity: 5,
    baseAtk: 741,
    lvl1BaseAtk: 49,
    subStat: { type: "atkPct", label: "ATK%", value: 16.5, baseValue: 3.6 },
    passiveName: "Pavonian Whispers",
    passiveDesc: "After the equipping character hits an opponent with a Plunging Attack, all nearby party members' Plunging Attacks deal 28~80% increased DMG for 20s. When nearby party members hit opponents with Plunging Attacks, they will restore 2.5~3.5 Energy to the equipping character.",
    isSupport: true,
    buffType: "both",
    buffs: [
      { id: "crane-party-plunge", label: "Party Plunging Attack DMG Bonus (Crane's Echoing Call)", description: "All nearby party members deal +28~80% increased Plunging Attack DMG", stat: "plungeDmgBonus", refinementValues: [28, 41, 54, 67, 80], isTeamBuff: true, computeCode: "(r) => [28, 41, 54, 67, 80][r - 1]" },
    ],
    signatureFor: ["xianyun"],
  },
  {
    name: "Crimson Moon's Semblance",
    type: "Polearm",
    rarity: 5,
    baseAtk: 674,
    lvl1BaseAtk: 48,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 22.1, baseValue: 4.8 },
    passiveName: "Ashen Sun's Shadow",
    passiveDesc: "Grants a Bond of Life equal to 25% of Max HP when a Charged Attack hits an opponent. When the equipping character has a Bond of Life, they gain 12~28% DMG Bonus; if the Bond of Life is >= 30% of Max HP, gain an additional 24~56% DMG.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [
      { id: "has-bol", label: "Wielder has Bond of Life (+12~28% DMG)", control: "toggle", defaultValue: 1, hint: "Active when any Bond of Life is present" },
      { id: "bol-ge-30", label: "Bond of Life >= 30% Max HP (+24~56% DMG)", control: "toggle", defaultValue: 1, hint: "Additional bonus when BoL is 30% or greater" },
    ],
    buffs: [
      { id: "crimson-moon-base-dmg", label: "All DMG Bonus (Bond of Life Active)", stat: "dmgBonus", refinementValues: [12, 16, 20, 24, 28], isTeamBuff: false, conditionKey: "has-bol", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['has-bol'] ?? '1') === '1' || Number(ctx.inputs?.['has-bol'] ?? 1) > 0; return on ? [12, 16, 20, 24, 28][r - 1] : 0; }" },
      { id: "crimson-moon-extra-dmg", label: "All DMG Bonus (BoL >= 30% Max HP)", stat: "dmgBonus", refinementValues: [24, 32, 40, 48, 56], isTeamBuff: false, conditionKey: "bol-ge-30", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['bol-ge-30'] ?? '1') === '1' || Number(ctx.inputs?.['bol-ge-30'] ?? 1) > 0; return on ? [24, 32, 40, 48, 56][r - 1] : 0; }" },
    ],
    signatureFor: ["arlecchino"],
  },
  {
    name: "Disaster and Remorse",
    type: "Polearm",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 66.2, baseValue: 14.4 },
    passiveName: "Mourning Veil",
    passiveDesc: "ATK is increased by 20~40%. When an Elemental Burst is unleashed, increases All Elemental DMG Bonus by 16~32% for 12s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "disaster-atk", label: "ATK%", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([20, 25, 30, 35, 40][r - 1] / 100) * ctx.baseAtk" },
      { id: "disaster-elem-dmg", label: "All Elemental DMG Bonus", stat: "dmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
    ],
  },
  {
    name: "Elegy for the End",
    type: "Bow",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "energyRecharge", label: "Energy Recharge%", value: 55.1, baseValue: 12.0 },
    passiveName: "The Parting Refrain",
    passiveDesc: "Increases Elemental Mastery by 60~120. When Elemental Skill/Burst hits 4 times, gain Millennial Movement: Farewell Song: increases Elemental Mastery by 100~200 and ATK by 20~40% for all party members for 12s.",
    isSupport: true,
    buffType: "both",
    mechanicDefs: [{ id: "elegy-sigils-active", label: "Farewell Song Active (4 Sigils)", control: "toggle", defaultValue: 1, hint: "Team buff: +100~200 EM and +20~40% ATK for 12s" }],
    buffs: [
      { id: "elegy-party-em", label: "Party EM (Elegy for the End)", description: "Nearby party members gain +100~200 Elemental Mastery", stat: "em", refinementValues: [100, 125, 150, 175, 200], isTeamBuff: true, conditionKey: "elegy-sigils-active", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['elegy-sigils-active'] ?? '1') === '1' || Number(ctx.inputs?.['elegy-sigils-active'] ?? 1) > 0; return on ? [100, 125, 150, 175, 200][r - 1] : 0; }" },
      { id: "elegy-party-atk", label: "Party ATK% (Elegy for the End)", description: "Nearby party members gain +20~40% ATK", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: true, isPercent: true, conditionKey: "elegy-sigils-active", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['elegy-sigils-active'] ?? '1') === '1' || Number(ctx.inputs?.['elegy-sigils-active'] ?? 1) > 0; return on ? ([20, 25, 30, 35, 40][r - 1] / 100) * ctx.baseAtk : 0; }" },
      { id: "elegy-self-em", label: "Self EM (Elegy for the End Base)", stat: "em", refinementValues: [60, 75, 90, 105, 120], isTeamBuff: false, computeCode: "(r) => [60, 75, 90, 105, 120][r - 1]" },
    ],
    signatureFor: ["venti"],
  },
  {
    name: "Engulfing Lightning",
    type: "Polearm",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "energyRecharge", label: "Energy Recharge%", value: 55.1, baseValue: 12.0 },
    passiveName: "Timeless Dream: Eternal Stove",
    passiveDesc: "ATK increased by 28~56% of Energy Recharge over the base 100%. You can gain a maximum bonus of 80~120% ATK. Gain 30~50% Energy Recharge for 12s after using an Elemental Burst.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [
      { id: "engulfing-total-er", label: "Character Total ER% (e.g. 250%)", control: "stacks", max: 400, defaultValue: 250, hint: "Total ER% used for Engulfing ATK conversion (over 100%)" },
      { id: "engulfing-burst-active", label: "Post-Burst +30~50% ER Active", control: "toggle", defaultValue: 1, hint: "+30~50% Energy Recharge for 12s" },
    ],
    buffs: [
      { id: "engulfing-atk-from-er", label: "ATK% from ER (Engulfing Lightning)", stat: "atk", refinementValues: [28, 35, 42, 49, 56], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => { const er = Number(ctx.inputs?.['engulfing-total-er'] ?? 250); const postBurst = (ctx.inputs?.['engulfing-burst-active'] ?? '1') === '1' || Number(ctx.inputs?.['engulfing-burst-active'] ?? 1) > 0; const totalEr = er + (postBurst ? [30, 35, 40, 45, 50][r - 1] : 0); const excessEr = Math.max(0, totalEr - 100); const ratio = [0.28, 0.35, 0.42, 0.49, 0.56][r - 1]; const cap = [80, 90, 100, 110, 120][r - 1]; const atkPct = Math.min(excessEr * ratio, cap); return (atkPct / 100) * ctx.baseAtk; }" },
      { id: "engulfing-er-buff", label: "Energy Recharge% (Engulfing Lightning)", stat: "energyRecharge", refinementValues: [30, 35, 40, 45, 50], isTeamBuff: false, conditionKey: "engulfing-burst-active", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['engulfing-burst-active'] ?? '1') === '1' || Number(ctx.inputs?.['engulfing-burst-active'] ?? 1) > 0; return on ? [30, 35, 40, 45, 50][r - 1] : 0; }" },
    ],
    signatureFor: ["raiden"],
  },
  {
    name: "Everlasting Moonglow",
    type: "Catalyst",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "hpPct", label: "HP%", value: 49.6, baseValue: 10.8 },
    passiveName: "Byakuya Kougetsu",
    passiveDesc: "Healing Bonus is increased by 10~20%, Normal Attack DMG is increased by 1~3% of the Max HP of the character equipping this weapon. For 12s after using an Elemental Burst, Normal Attacks that hit opponents will restore 0.6 Energy.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "moonglow-max-hp", label: "Character Max HP", control: "stacks", max: 100000, defaultValue: 40000, hint: "Max HP used for flat NA DMG calculation" }],
    buffs: [
      { id: "moonglow-heal", label: "Healing Bonus% (Everlasting Moonglow)", stat: "healingBonus", refinementValues: [10, 12.5, 15, 17.5, 20], isTeamBuff: false, computeCode: "(r) => [10, 12.5, 15, 17.5, 20][r - 1]" },
      { id: "moonglow-flat-na", label: "Flat Normal Attack DMG from HP (Everlasting Moonglow)", stat: "normalDmgBonus", refinementValues: [1, 1.5, 2, 2.5, 3], isTeamBuff: false, computeCode: "(r, ctx) => { const hp = Number(ctx.inputs?.['moonglow-max-hp'] ?? 40000); const ratio = [0.01, 0.015, 0.02, 0.025, 0.03][r - 1]; return hp * ratio; }" },
    ],
    signatureFor: ["sangonomiya-kokomi"],
  },
  {
    name: "Exaiphanes Blade",
    type: "Sword",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 33.1, baseValue: 7.2 },
    passiveName: "Sudden Manifestation",
    passiveDesc: "Increases All Elemental DMG Bonus by 12~24%. After using an Elemental Skill, increases Normal and Charged Attack DMG by 20~40% for 10s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "exaiphanes-elem-dmg", label: "All Elemental DMG Bonus", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "exaiphanes-na-ca", label: "Normal/Charged Attack DMG Bonus", stat: "normalDmgBonus", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
    ],
  },
  {
    name: "Fang of the Mountain King",
    type: "Claymore",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 33.1, baseValue: 7.2 },
    passiveName: "Turquoise Dawn",
    passiveDesc: "Gain 1 stack of Canopy's Favor when an Elemental Skill hits an opponent. Max 6 stacks. At 6 stacks, Elemental Skill and Elemental Burst DMG is increased by 48~96%.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "mountain-king-stacks", label: "Canopy's Favor Stacks (0-6)", control: "stacks", max: 6, defaultValue: 6, hint: "+8~16% Skill & Burst DMG per stack (up to +48~96%)" }],
    buffs: [
      { id: "mountain-king-skill-dmg", label: "Elemental Skill DMG Bonus (Fang of Mountain King)", stat: "skillDmgBonus", refinementValues: [48, 60, 72, 84, 96], isTeamBuff: false, conditionKey: "mountain-king-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['mountain-king-stacks'] ?? 6); return s * [8, 10, 12, 14, 16][r - 1]; }" },
      { id: "mountain-king-burst-dmg", label: "Elemental Burst DMG Bonus (Fang of Mountain King)", stat: "burstDmgBonus", refinementValues: [48, 60, 72, 84, 96], isTeamBuff: false, conditionKey: "mountain-king-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['mountain-king-stacks'] ?? 6); return s * [8, 10, 12, 14, 16][r - 1]; }" },
    ],
    signatureFor: ["kinich"],
  },
  {
    name: "Fractured Halo",
    type: "Polearm",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 66.2, baseValue: 14.4 },
    passiveName: "Broken Orbit",
    passiveDesc: "Increases All Elemental DMG Bonus by 12~24%. When an Elemental Skill hits an opponent, ATK is increased by 16~32% for 10s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "fractured-halo-elem-dmg", label: "All Elemental DMG Bonus", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "fractured-halo-atk", label: "ATK%", stat: "atk", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([16, 20, 24, 28, 32][r - 1] / 100) * ctx.baseAtk" },
    ],
  },
  {
    name: "Freedom-Sworn",
    type: "Sword",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "em", label: "Elemental Mastery", value: 198, baseValue: 43 },
    passiveName: "Revolutionary Chorale",
    passiveDesc: "Increases DMG by 10~20%. When triggering Elemental Reactions 2 times, all nearby party members gain +16~32% Normal/Charged/Plunging Attack DMG and +20~40% ATK for 12s.",
    isSupport: true,
    buffType: "both",
    mechanicDefs: [{ id: "freedom-sigils-active", label: "Millennial Movement: Song of Resistance Active", control: "toggle", defaultValue: 1, hint: "Team buff: +16~32% NA/CA/Plunge DMG, +20~40% ATK for 12s" }],
    buffs: [
      { id: "freedom-party-na-ca-plunge", label: "Party NA/CA/Plunge DMG Bonus (Freedom-Sworn)", description: "Nearby party members gain +16~32% Normal, Charged, and Plunging Attack DMG", stat: "normalDmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: true, conditionKey: "freedom-sigils-active", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['freedom-sigils-active'] ?? '1') === '1' || Number(ctx.inputs?.['freedom-sigils-active'] ?? 1) > 0; return on ? [16, 20, 24, 28, 32][r - 1] : 0; }" },
      { id: "freedom-party-charged", label: "Party Charged Attack DMG Bonus (Freedom-Sworn)", stat: "chargedDmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: true, conditionKey: "freedom-sigils-active", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['freedom-sigils-active'] ?? '1') === '1' || Number(ctx.inputs?.['freedom-sigils-active'] ?? 1) > 0; return on ? [16, 20, 24, 28, 32][r - 1] : 0; }" },
      { id: "freedom-party-plunge", label: "Party Plunging Attack DMG Bonus (Freedom-Sworn)", stat: "plungeDmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: true, conditionKey: "freedom-sigils-active", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['freedom-sigils-active'] ?? '1') === '1' || Number(ctx.inputs?.['freedom-sigils-active'] ?? 1) > 0; return on ? [16, 20, 24, 28, 32][r - 1] : 0; }" },
      { id: "freedom-party-atk", label: "Party ATK% (Freedom-Sworn)", description: "Nearby party members gain +20~40% ATK", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: true, isPercent: true, conditionKey: "freedom-sigils-active", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['freedom-sigils-active'] ?? '1') === '1' || Number(ctx.inputs?.['freedom-sigils-active'] ?? 1) > 0; return on ? ([20, 25, 30, 35, 40][r - 1] / 100) * ctx.baseAtk : 0; }" },
      { id: "freedom-self-dmg", label: "Self All DMG Bonus (Freedom-Sworn Base)", stat: "dmgBonus", refinementValues: [10, 12.5, 15, 17.5, 20], isTeamBuff: false, computeCode: "(r) => [10, 12.5, 15, 17.5, 20][r - 1]" },
    ],
    signatureFor: ["kaedehara-kazuha"],
  },
  {
    name: "Gest of the Mighty Wolf",
    type: "Claymore",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 33.1, baseValue: 7.2 },
    passiveName: "Wolf's Song",
    passiveDesc: "Increases All Elemental DMG Bonus by 12~24%. Normal and Charged Attack hits increase ATK by 16~32% for 8s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "mighty-wolf-elem-dmg", label: "All Elemental DMG Bonus", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "mighty-wolf-atk", label: "ATK%", stat: "atk", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([16, 20, 24, 28, 32][r - 1] / 100) * ctx.baseAtk" },
    ],
  },
  {
    name: "Golden Frostbound Oath",
    type: "Polearm",
    rarity: 5,
    baseAtk: 674,
    lvl1BaseAtk: 48,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 44.1, baseValue: 9.6 },
    passiveName: "Frostbound Oath",
    passiveDesc: "ATK is increased by 20~40%. When an Elemental Burst is used, increases Cryo DMG Bonus by 20~40% for 12s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "frostbound-oath-atk", label: "ATK%", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([20, 25, 30, 35, 40][r - 1] / 100) * ctx.baseAtk" },
      { id: "frostbound-oath-cryo", label: "Cryo DMG Bonus", stat: "cryoDmgBonus", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
    ],
  },
  {
    name: "Haran Geppaku Futsu",
    type: "Sword",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 33.1, baseValue: 7.2 },
    passiveName: "Honed Flow",
    passiveDesc: "Obtain 12~24% All Elemental DMG Bonus. When nearby party members use Elemental Skills, obtain 1 Wavespike stack (max 2). When the wielder uses an Elemental Skill, consume all stacks to gain 20~40% Normal Attack DMG Bonus per stack for 8s.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "wavespike-stacks", label: "Wavespike Stacks Consumed (0-2)", control: "stacks", max: 2, defaultValue: 2, hint: "+20~40% Normal Attack DMG Bonus per stack" }],
    buffs: [
      { id: "haran-elem-dmg", label: "All Elemental DMG Bonus (Haran Geppaku Futsu)", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "haran-na-dmg", label: "Normal Attack DMG Bonus (Haran Wavespike)", stat: "normalDmgBonus", refinementValues: [40, 50, 60, 70, 80], isTeamBuff: false, conditionKey: "wavespike-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['wavespike-stacks'] ?? 2); return s * [20, 25, 30, 35, 40][r - 1]; }" },
    ],
    signatureFor: ["kamisato-ayato"],
  },
  {
    name: "Hunter's Path",
    type: "Bow",
    rarity: 5,
    baseAtk: 542,
    lvl1BaseAtk: 44,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 44.1, baseValue: 9.6 },
    passiveName: "At the End of the Beast-Paths",
    passiveDesc: "Gain 12~24% All Elemental DMG Bonus. Obtain the Tireless Hunt effect after hitting an opponent with a Charged Attack: Charged Attack DMG is increased by 160~320% of Elemental Mastery for 12 hits or 10s.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [
      { id: "hunters-path-em", label: "Character EM", control: "stacks", max: 2000, defaultValue: 400, hint: "EM used for flat Charged Attack DMG bonus" },
      { id: "hunters-path-active", label: "Tireless Hunt Active", control: "toggle", defaultValue: 1, hint: "+160~320% of EM as flat CA DMG bonus" },
    ],
    buffs: [
      { id: "hunters-path-elem-dmg", label: "All Elemental DMG Bonus (Hunter's Path)", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "hunters-path-flat-ca", label: "Flat CA DMG from EM (Hunter's Path)", stat: "flatDmgBonus", refinementValues: [160, 200, 240, 280, 320], isTeamBuff: false, conditionKey: "hunters-path-active", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['hunters-path-active'] ?? '1') === '1' || Number(ctx.inputs?.['hunters-path-active'] ?? 1) > 0; if (!on) return 0; const em = Number(ctx.inputs?.['hunters-path-em'] ?? 400); return em * ([1.6, 2.0, 2.4, 2.8, 3.2][r - 1]); }" },
    ],
    signatureFor: ["tighnari"],
  },
  {
    name: "Jadefall's Splendor",
    type: "Catalyst",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "hpPct", label: "HP%", value: 49.6, baseValue: 10.8 },
    passiveName: "Primordial Jade Regalia",
    passiveDesc: "For 3s after using an Elemental Burst or creating a shield, the equipping character can gain the Primordial Jade Regalia effect: Restore 4.5~6.5 Energy every 2.5s, and gain 0.3~1.1% Elemental DMG Bonus for their corresponding Elemental Type for every 1,000 Max HP they possess, up to 12~44%.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "jadefall-max-hp", label: "Character Max HP", control: "stacks", max: 100000, defaultValue: 50000, hint: "Max HP used for Elemental DMG Bonus conversion" }],
    buffs: [
      { id: "jadefall-elem-dmg", label: "Elemental DMG Bonus (Jadefall's Splendor)", stat: "dmgBonus", refinementValues: [12, 20, 28, 36, 44], isTeamBuff: false, computeCode: "(r, ctx) => { const hp = Number(ctx.inputs?.['jadefall-max-hp'] ?? 50000); const per1k = [0.3, 0.5, 0.7, 0.9, 1.1][r - 1]; const cap = [12, 20, 28, 36, 44][r - 1]; return Math.min((hp / 1000) * per1k, cap); }" },
    ],
    signatureFor: ["baizhu"],
  },
  {
    name: "Kagura's Verity",
    type: "Catalyst",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 66.2, baseValue: 14.4 },
    passiveName: "Kagura Dance",
    passiveDesc: "Gains the Kagura Dance effect when using an Elemental Skill, causing the Elemental Skill DMG of the character equipping this weapon to increase by 12~24% for 16s. Max 3 stacks. At 3 stacks, this character will gain 12~24% All Elemental DMG Bonus.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "kagura-stacks", label: "Kagura Dance Stacks (0-3)", control: "stacks", max: 3, defaultValue: 3, hint: "+12~24% Skill DMG per stack; +12~24% All Elem DMG at 3 stacks" }],
    buffs: [
      { id: "kagura-skill-dmg", label: "Elemental Skill DMG Bonus (Kagura's Verity)", stat: "skillDmgBonus", refinementValues: [36, 45, 54, 63, 72], isTeamBuff: false, conditionKey: "kagura-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['kagura-stacks'] ?? 3); return s * [12, 15, 18, 21, 24][r - 1]; }" },
      { id: "kagura-elem-dmg", label: "All Elemental DMG Bonus (Kagura Max Stacks)", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, conditionKey: "kagura-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['kagura-stacks'] ?? 3); return s >= 3 ? [12, 15, 18, 21, 24][r - 1] : 0; }" },
    ],
    signatureFor: ["yae-miko"],
  },
  {
    name: "Key of Khaj-Nisut",
    type: "Sword",
    rarity: 5,
    baseAtk: 542,
    lvl1BaseAtk: 44,
    subStat: { type: "hpPct", label: "HP%", value: 66.2, baseValue: 14.4 },
    passiveName: "Sunken Song of the Sands",
    passiveDesc: "HP increased by 20~40%. When an Elemental Skill hits opponents, gain Grand Hymn effect for 20s (max 3 stacks): increases EM by 0.12~0.24% of Max HP per stack. At 3 stacks, all nearby party members gain EM equal to 0.2~0.4% of wielder's Max HP for 20s.",
    isSupport: true,
    buffType: "both",
    mechanicDefs: [
      { id: "wielder-max-hp", label: "Wielder's Max HP (e.g. 70000)", control: "stacks", max: 100000, defaultValue: 70000, hint: "Used to calculate EM granted to party members" },
      { id: "key-hymn-stacks", label: "Grand Hymn Stacks (0-3)", control: "stacks", max: 3, defaultValue: 3, hint: "3 stacks required to activate party EM buff" },
    ],
    buffs: [
      { id: "key-self-hp", label: "HP% (Key of Khaj-Nisut Base)", stat: "hp", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
      { id: "key-self-em", label: "Self EM from Max HP (Key of Khaj-Nisut)", stat: "em", refinementValues: [0.36, 0.45, 0.54, 0.63, 0.72], isTeamBuff: false, conditionKey: "key-hymn-stacks", computeCode: "(r, ctx) => { const hp = Number(ctx.inputs?.['wielder-max-hp'] ?? 70000); const s = Number(ctx.inputs?.['key-hymn-stacks'] ?? 3); const perStack = [0.0012, 0.0015, 0.0018, 0.0021, 0.0024][r - 1]; return hp * perStack * s; }" },
      { id: "key-party-em", label: "Party EM from Wielder Max HP (Key of Khaj-Nisut)", description: "Nearby party members gain EM equal to 0.2~0.4% of wielder's Max HP", stat: "em", refinementValues: [0.2, 0.25, 0.3, 0.35, 0.4], isTeamBuff: true, conditionKey: "key-hymn-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['key-hymn-stacks'] ?? 3); if (s < 3) return 0; const hp = Number(ctx.inputs?.['wielder-max-hp'] ?? 70000); const ratio = [0.002, 0.0025, 0.003, 0.0035, 0.004][r - 1]; return hp * ratio; }" },
    ],
    signatureFor: ["nilou"],
  },
  {
    name: "Light of Foliar Incision",
    type: "Sword",
    rarity: 5,
    baseAtk: 542,
    lvl1BaseAtk: 44,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 88.2, baseValue: 19.2 },
    passiveName: "Whitemoon Bristle",
    passiveDesc: "CRIT Rate is increased by 4~8%. After Normal Attacks deal Elemental DMG, the Foliar Incision effect is obtained: increases DMG dealt by Normal Attacks and Elemental Skills by 120~240% of Elemental Mastery for 28 hits or 12s.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [
      { id: "foliar-wielder-em", label: "Character EM", control: "stacks", max: 2000, defaultValue: 400, hint: "EM used for Foliar Incision flat DMG" },
      { id: "foliar-incision-active", label: "Foliar Incision Active", control: "toggle", defaultValue: 1, hint: "+120~240% of EM as flat NA/Skill DMG" },
    ],
    buffs: [
      { id: "foliar-crit-rate", label: "CRIT Rate% (Light of Foliar Incision)", stat: "critRate", refinementValues: [4, 5, 6, 7, 8], isTeamBuff: false, computeCode: "(r) => [4, 5, 6, 7, 8][r - 1]" },
      { id: "foliar-na-flat", label: "Normal Attack Flat DMG from EM", stat: "normalDmgBonus", refinementValues: [120, 150, 180, 210, 240], isTeamBuff: false, conditionKey: "foliar-incision-active", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['foliar-incision-active'] ?? '1') === '1' || Number(ctx.inputs?.['foliar-incision-active'] ?? 1) > 0; if (!on) return 0; const em = Number(ctx.inputs?.['foliar-wielder-em'] ?? 400); return em * ([1.2, 1.5, 1.8, 2.1, 2.4][r - 1]); }" },
      { id: "foliar-skill-flat", label: "Elemental Skill Flat DMG from EM", stat: "skillDmgBonus", refinementValues: [120, 150, 180, 210, 240], isTeamBuff: false, conditionKey: "foliar-incision-active", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['foliar-incision-active'] ?? '1') === '1' || Number(ctx.inputs?.['foliar-incision-active'] ?? 1) > 0; if (!on) return 0; const em = Number(ctx.inputs?.['foliar-wielder-em'] ?? 400); return em * ([1.2, 1.5, 1.8, 2.1, 2.4][r - 1]); }" },
    ],
    signatureFor: ["alhaitham"],
  },
  {
    name: "Lightbearing Moonshard",
    type: "Sword",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 33.1, baseValue: 7.2 },
    passiveName: "Lunar Glow",
    passiveDesc: "All Elemental DMG Bonus is increased by 12~24%. When an Elemental Burst is used, increases ATK by 20~40% for 12s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "moonshard-elem-dmg", label: "All Elemental DMG Bonus", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "moonshard-atk", label: "ATK%", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([20, 25, 30, 35, 40][r - 1] / 100) * ctx.baseAtk" },
    ],
  },
  {
    name: "Lost Prayer to the Sacred Winds",
    type: "Catalyst",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 33.1, baseValue: 7.2 },
    passiveName: "Boundless Blessing",
    passiveDesc: "Increases Movement SPD by 10%. When in battle, gain an 8~16% Elemental DMG Bonus every 4s. Max 4 stacks. Lasts until the character falls or leaves combat.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "lost-prayer-stacks", label: "On-Field Time Stacks (0-4)", control: "stacks", max: 4, defaultValue: 4, hint: "+8~16% Elemental DMG Bonus every 4s (up to +32~64%)" }],
    buffs: [
      { id: "lost-prayer-elem-dmg", label: "Elemental DMG Bonus (Lost Prayer)", stat: "dmgBonus", refinementValues: [32, 40, 48, 56, 64], isTeamBuff: false, conditionKey: "lost-prayer-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['lost-prayer-stacks'] ?? 4); return s * [8, 10, 12, 14, 16][r - 1]; }" },
    ],
  },
  {
    name: "Lumidouce Elegy",
    type: "Polearm",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 33.1, baseValue: 7.2 },
    passiveName: "Bright Dawn Overlay",
    passiveDesc: "ATK is increased by 15~30%. After the equipping character triggers Burning on an opponent or deals Dendro DMG to Burning opponents, the DMG dealt is increased by 18~36% for 8s. Max 2 stacks. At 2 stacks or when 2 stacks refresh, restore 12~16 Energy.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "lumidouce-stacks", label: "Burning Stacks (0-2)", control: "stacks", max: 2, defaultValue: 2, hint: "+18~36% All DMG bonus per stack (up to +36~72%)" }],
    buffs: [
      { id: "lumidouce-atk", label: "ATK% (Lumidouce Elegy)", stat: "atk", refinementValues: [15, 18.75, 22.5, 26.25, 30], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([15, 18.75, 22.5, 26.25, 30][r - 1] / 100) * ctx.baseAtk" },
      { id: "lumidouce-dmg", label: "All DMG Bonus (Lumidouce Elegy Stacks)", stat: "dmgBonus", refinementValues: [36, 45, 54, 63, 72], isTeamBuff: false, conditionKey: "lumidouce-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['lumidouce-stacks'] ?? 2); return s * [18, 22.5, 27, 31.5, 36][r - 1]; }" },
    ],
    signatureFor: ["emilie"],
  },
  {
    name: "Memory of Dust",
    type: "Catalyst",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "atkPct", label: "ATK%", value: 49.6, baseValue: 10.8 },
    passiveName: "Golden Majesty",
    passiveDesc: "Increases Shield Strength by 20~40%. Scoring hits on opponents increases ATK by 4~8% for 8s. Max 5 stacks. While protected by a shield, this ATK increase effect is increased by 100%.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [
      { id: "memory-dust-stacks", label: "Golden Majesty Stacks (0-5)", control: "stacks", max: 5, defaultValue: 5, hint: "+4~8% ATK per stack" },
      { id: "memory-dust-shielded", label: "Protected by Shield (2x ATK Buff)", control: "toggle", defaultValue: 1, hint: "Doubles ATK bonus from stacks" },
    ],
    buffs: [
      { id: "memory-dust-atk", label: "ATK% (Memory of Dust Stacks)", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, conditionKey: "memory-dust-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['memory-dust-stacks'] ?? 5); const shielded = (ctx.inputs?.['memory-dust-shielded'] ?? '1') === '1' || Number(ctx.inputs?.['memory-dust-shielded'] ?? 1) > 0; const mult = shielded ? 2 : 1; return ((s * [4, 5, 6, 7, 8][r - 1] * mult) / 100) * ctx.baseAtk; }" },
    ],
  },
  {
    name: "Mistsplitter Reforged",
    type: "Sword",
    rarity: 5,
    baseAtk: 674,
    lvl1BaseAtk: 48,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 44.1, baseValue: 9.6 },
    passiveName: "Mistsplitter's Edge",
    passiveDesc: "Gain 12~24% Elemental DMG Bonus for all elements and receive the might of the Mistsplitter's Emblem. At stack levels 1/2/3, Mistsplitter's Emblem provides 8/16/28% ~ 16/32/56% Elemental DMG Bonus for the character's Elemental Type.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "mistsplitter-stacks", label: "Mistsplitter's Emblem Stacks (0-3)", control: "stacks", max: 3, defaultValue: 3, hint: "+8/16/28% Elemental DMG Bonus at R1 (up to +16/32/56% at R5)" }],
    buffs: [
      { id: "mistsplitter-base-elem", label: "All Elemental DMG Bonus (Mistsplitter Base)", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "mistsplitter-emblem-dmg", label: "Elemental DMG Bonus (Mistsplitter Stacks)", stat: "dmgBonus", refinementValues: [28, 35, 42, 49, 56], isTeamBuff: false, conditionKey: "mistsplitter-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['mistsplitter-stacks'] ?? 3); const tiers: Record<number, [number, number, number, number, number]> = { 0: [0, 0, 0, 0, 0], 1: [8, 10, 12, 14, 16], 2: [16, 20, 24, 28, 32], 3: [28, 35, 42, 49, 56] }; return (tiers[s] ?? tiers[3])[r - 1]; }" },
    ],
    signatureFor: ["kamisato-ayaka"],
  },
  {
    name: "Nightweaver's Looking Glass",
    type: "Catalyst",
    rarity: 5,
    baseAtk: 542,
    lvl1BaseAtk: 44,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 88.2, baseValue: 19.2 },
    passiveName: "Nocturnal Vision",
    passiveDesc: "Increases All Elemental DMG Bonus by 12~24%. When an Elemental Burst hits opponents, increases Elemental Mastery by 80~160 for 12s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "nightweaver-elem-dmg", label: "All Elemental DMG Bonus", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "nightweaver-em", label: "Elemental Mastery", stat: "em", refinementValues: [80, 100, 120, 140, 160], isTeamBuff: false, computeCode: "(r) => [80, 100, 120, 140, 160][r - 1]" },
    ],
  },
  {
    name: "Nocturne's Curtain Call",
    type: "Catalyst",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 33.1, baseValue: 7.2 },
    passiveName: "Curtain Call",
    passiveDesc: "All Elemental DMG Bonus is increased by 12~24%. After using an Elemental Skill, increases Normal and Charged Attack DMG by 20~40% for 10s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "nocturne-elem-dmg", label: "All Elemental DMG Bonus", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "nocturne-na-ca", label: "Normal/Charged Attack DMG Bonus", stat: "normalDmgBonus", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
    ],
  },
  {
    name: "Peak Patrol Song",
    type: "Sword",
    rarity: 5,
    baseAtk: 542,
    lvl1BaseAtk: 44,
    subStat: { type: "defPct", label: "DEF%", value: 82.7, baseValue: 18.0 },
    passiveName: "High-Altitude Patrol",
    passiveDesc: "After Normal or Plunging Attacks hit opponents, gain the Ode to Flowers effect: DEF is increased by 8~16% and All Elemental DMG Bonus by 10~20% for 6s (max 2 stacks). At 2 stacks, every 1,000 DEF increases nearby party members' All Elemental DMG Bonus by 8~16% for 15s (max 25.6~51.2%).",
    isSupport: true,
    buffType: "both",
    mechanicDefs: [
      { id: "patrol-wielder-def", label: "Wielder's DEF (e.g. 3200)", control: "stacks", max: 6000, defaultValue: 3200, hint: "DEF used for party Elemental DMG Bonus conversion (cap reached at 3200 DEF)" },
      { id: "patrol-ode-stacks", label: "Ode to Flowers Stacks (0-2)", control: "stacks", max: 2, defaultValue: 2, hint: "2 stacks trigger party Elemental DMG buff" },
    ],
    buffs: [
      { id: "patrol-party-elem-dmg", label: "Party All Elemental DMG Bonus (Peak Patrol Song)", description: "Nearby party members gain All Elemental DMG Bonus based on wielder's DEF", stat: "dmgBonus", refinementValues: [25.6, 32.0, 38.4, 44.8, 51.2], isTeamBuff: true, conditionKey: "patrol-ode-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['patrol-ode-stacks'] ?? 2); if (s < 2) return 0; const def = Number(ctx.inputs?.['patrol-wielder-def'] ?? 3200); const per1k = [8, 10, 12, 14, 16][r - 1]; const cap = [25.6, 32.0, 38.4, 44.8, 51.2][r - 1]; return Math.min((def / 1000) * per1k, cap); }" },
      { id: "patrol-self-def", label: "Self DEF% (Peak Patrol Song)", stat: "def", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, isPercent: true, conditionKey: "patrol-ode-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['patrol-ode-stacks'] ?? 2); return s * [8, 10, 12, 14, 16][r - 1]; }" },
      { id: "patrol-self-dmg", label: "Self All Elemental DMG Bonus (Peak Patrol Song)", stat: "dmgBonus", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, conditionKey: "patrol-ode-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['patrol-ode-stacks'] ?? 2); return s * [10, 12.5, 15, 17.5, 20][r - 1]; }" },
    ],
    signatureFor: ["xilonen"],
  },
  {
    name: "Polar Star",
    type: "Bow",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 33.1, baseValue: 7.2 },
    passiveName: "Daylight's Augur",
    passiveDesc: "Elemental Skill and Elemental Burst DMG increased by 12~24%. Normal Attack, Charged Attack, Elemental Skill, and Elemental Burst each grant 1 stack of Ashen Nightstar on hit for 12s. At 1/2/3/4 stacks, ATK is increased by 10/20/30/48% ~ 20/40/60/96%.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "polar-star-stacks", label: "Ashen Nightstar Stacks (0-4)", control: "stacks", max: 4, defaultValue: 4, hint: "Tiered ATK% bonus (10/20/30/48% at R1, up to 20/40/60/96% at R5)" }],
    buffs: [
      { id: "polar-skill-dmg", label: "Elemental Skill DMG Bonus (Polar Star)", stat: "skillDmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "polar-burst-dmg", label: "Elemental Burst DMG Bonus (Polar Star)", stat: "burstDmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "polar-atk", label: "ATK% (Polar Star Nightstar Stacks)", stat: "atk", refinementValues: [48, 60, 72, 84, 96], isTeamBuff: false, isPercent: true, conditionKey: "polar-star-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['polar-star-stacks'] ?? 4); const tiers: Record<number, [number, number, number, number, number]> = { 0: [0, 0, 0, 0, 0], 1: [10, 12.5, 15, 17.5, 20], 2: [20, 25, 30, 35, 40], 3: [30, 37.5, 45, 52.5, 60], 4: [48, 60, 72, 84, 96] }; const pct = (tiers[s] ?? tiers[4])[r - 1]; return (pct / 100) * ctx.baseAtk; }" },
    ],
    signatureFor: ["tartaglia"],
  },
  {
    name: "Primordial Jade Cutter",
    type: "Sword",
    rarity: 5,
    baseAtk: 542,
    lvl1BaseAtk: 44,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 44.1, baseValue: 9.6 },
    passiveName: "Protector's Virtue",
    passiveDesc: "HP is increased by 20~40%. Additionally, provides an ATK Bonus based on 1.2~2.4% of the wielder's Max HP.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "jade-cutter-max-hp", label: "Character Max HP", control: "stacks", max: 100000, defaultValue: 25000, hint: "Max HP used for flat ATK conversion" }],
    buffs: [
      { id: "jade-cutter-hp", label: "HP% (Primordial Jade Cutter)", stat: "hp", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
      { id: "jade-cutter-atk-from-hp", label: "Flat ATK from Max HP (Primordial Jade Cutter)", stat: "atk", refinementValues: [1.2, 1.5, 1.8, 2.1, 2.4], isTeamBuff: false, computeCode: "(r, ctx) => { const hp = Number(ctx.inputs?.['jade-cutter-max-hp'] ?? 25000); const ratio = [0.012, 0.015, 0.018, 0.021, 0.024][r - 1]; return hp * ratio; }" },
    ],
  },
  {
    name: "Primordial Jade Winged-Spear",
    type: "Polearm",
    rarity: 5,
    baseAtk: 674,
    lvl1BaseAtk: 48,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 22.1, baseValue: 4.8 },
    passiveName: "Eagle Spear of Justice",
    passiveDesc: "On hit, increases ATK by 3.2~6.0% for 6s. Max 7 stacks. This effect can only occur once every 0.3s. While in possession of the maximum possible stacks, DMG dealt is increased by 12~24%.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "pjws-stacks", label: "Eagle Spear Stacks (0-7)", control: "stacks", max: 7, defaultValue: 7, hint: "+3.2~6.0% ATK per hit stack; +12~24% All DMG at 7 stacks" }],
    buffs: [
      { id: "pjws-atk", label: "ATK% (Primordial Jade Winged-Spear Stacks)", stat: "atk", refinementValues: [22.4, 27.3, 32.2, 37.1, 42.0], isTeamBuff: false, isPercent: true, conditionKey: "pjws-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['pjws-stacks'] ?? 7); const perStack = [3.2, 3.9, 4.6, 5.3, 6.0][r - 1]; return ((s * perStack) / 100) * ctx.baseAtk; }" },
      { id: "pjws-full-stack-dmg", label: "All DMG Bonus (PJWS Max Stacks)", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, conditionKey: "pjws-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['pjws-stacks'] ?? 7); return s >= 7 ? [12, 15, 18, 21, 24][r - 1] : 0; }" },
    ],
    signatureFor: ["xiao"],
  },
  {
    name: "Redhorn Stonethresher",
    type: "Claymore",
    rarity: 5,
    baseAtk: 542,
    lvl1BaseAtk: 44,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 88.2, baseValue: 19.2 },
    passiveName: "Gokadaiou Otogibanashi",
    passiveDesc: "DEF is increased by 28~56%. Normal and Charged Attack DMG is increased by 40~80% of DEF.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "redhorn-wielder-def", label: "Character Total DEF", control: "stacks", max: 6000, defaultValue: 2500, hint: "Total DEF used for flat NA/CA DMG bonus" }],
    buffs: [
      { id: "redhorn-def", label: "DEF% (Redhorn Stonethresher)", stat: "def", refinementValues: [28, 35, 42, 49, 56], isTeamBuff: false, isPercent: true, computeCode: "(r) => [28, 35, 42, 49, 56][r - 1]" },
      { id: "redhorn-na-dmg", label: "Flat Normal Attack DMG from DEF (Redhorn)", stat: "normalDmgBonus", refinementValues: [40, 50, 60, 70, 80], isTeamBuff: false, computeCode: "(r, ctx) => { const def = Number(ctx.inputs?.['redhorn-wielder-def'] ?? 2500); const ratio = [0.4, 0.5, 0.6, 0.7, 0.8][r - 1]; return def * ratio; }" },
      { id: "redhorn-ca-dmg", label: "Flat Charged Attack DMG from DEF (Redhorn)", stat: "chargedDmgBonus", refinementValues: [40, 50, 60, 70, 80], isTeamBuff: false, computeCode: "(r, ctx) => { const def = Number(ctx.inputs?.['redhorn-wielder-def'] ?? 2500); const ratio = [0.4, 0.5, 0.6, 0.7, 0.8][r - 1]; return def * ratio; }" },
    ],
    signatureFor: ["arataki-itto"],
  },
  {
    name: "Reliquary of Truth",
    type: "Catalyst",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 33.1, baseValue: 7.2 },
    passiveName: "Truth Seeker",
    passiveDesc: "Increases All Elemental DMG Bonus by 12~24%. When triggering an Elemental Reaction, increases Elemental Mastery by 80~160 for 10s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "reliquary-elem-dmg", label: "All Elemental DMG Bonus", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "reliquary-em", label: "Elemental Mastery", stat: "em", refinementValues: [80, 100, 120, 140, 160], isTeamBuff: false, computeCode: "(r) => [80, 100, 120, 140, 160][r - 1]" },
    ],
  },
  {
    name: "Silvershower Heartstrings",
    type: "Bow",
    rarity: 5,
    baseAtk: 542,
    lvl1BaseAtk: 44,
    subStat: { type: "hpPct", label: "HP%", value: 66.2, baseValue: 14.4 },
    passiveName: "Dry-Well Receding",
    passiveDesc: "The equipping character can gain the Remedy effect: Providing healing, using an Elemental Skill, or when protected by a Bond of Life increases Max HP by 12/24/40% ~ 24/48/80% at 1/2/3 stacks for 25s. At 3 stacks, Elemental Burst CRIT Rate is increased by 28~56%.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "silvershower-stacks", label: "Remedy Stacks (0-3)", control: "stacks", max: 3, defaultValue: 3, hint: "+12/24/40% Max HP; +28~56% Burst CRIT Rate at 3 stacks" }],
    buffs: [
      { id: "silvershower-hp", label: "Max HP% (Silvershower Heartstrings)", stat: "hp", refinementValues: [40, 50, 60, 70, 80], isTeamBuff: false, isPercent: true, conditionKey: "silvershower-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['silvershower-stacks'] ?? 3); const tiers: Record<number, [number, number, number, number, number]> = { 0: [0, 0, 0, 0, 0], 1: [12, 15, 18, 21, 24], 2: [24, 30, 36, 42, 48], 3: [40, 50, 60, 70, 80] }; return (tiers[s] ?? tiers[3])[r - 1]; }" },
      { id: "silvershower-burst-crit", label: "Elemental Burst CRIT Rate% (Silvershower)", stat: "critRate", refinementValues: [28, 35, 42, 49, 56], isTeamBuff: false, conditionKey: "silvershower-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['silvershower-stacks'] ?? 3); return s >= 3 ? [28, 35, 42, 49, 56][r - 1] : 0; }" },
    ],
    signatureFor: ["sigewinne"],
  },
  {
    name: "Skyward Atlas",
    type: "Catalyst",
    rarity: 5,
    baseAtk: 674,
    lvl1BaseAtk: 48,
    subStat: { type: "atkPct", label: "ATK%", value: 33.1, baseValue: 7.2 },
    passiveName: "Wandering Clouds",
    passiveDesc: "Increases Elemental DMG Bonus by 12~24%. Normal Attack hits have a 50% chance to earn the favor of the clouds, actively seeking surrounding opponents to deal 160~320% ATK DMG for 15s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "skyward-atlas-elem-dmg", label: "All Elemental DMG Bonus (Skyward Atlas)", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
    ],
  },
  {
    name: "Skyward Blade",
    type: "Sword",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "energyRecharge", label: "Energy Recharge%", value: 55.1, baseValue: 12.0 },
    passiveName: "Sky-Piercing Fang",
    passiveDesc: "CRIT Rate is increased by 4~8%. Using an Elemental Burst gains Skypiercing Might: increases Movement SPD by 10%, ATK SPD by 10%, and Normal and Charged Attacks deal additional DMG equal to 20~40% of ATK for 12s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "skyward-blade-crit", label: "CRIT Rate% (Skyward Blade)", stat: "critRate", refinementValues: [4, 5, 6, 7, 8], isTeamBuff: false, computeCode: "(r) => [4, 5, 6, 7, 8][r - 1]" },
    ],
    signatureFor: ["bennett"],
  },
  {
    name: "Skyward Harp",
    type: "Bow",
    rarity: 5,
    baseAtk: 674,
    lvl1BaseAtk: 48,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 22.1, baseValue: 4.8 },
    passiveName: "Echoing Ballad",
    passiveDesc: "Increases CRIT DMG by 20~40%. Hits have a 60~100% chance to inflict a small AoE attack dealing 125% Physical ATK DMG every 4~2s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "skyward-harp-crit-dmg", label: "CRIT DMG% (Skyward Harp)", stat: "critDmg", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
    ],
  },
  {
    name: "Skyward Pride",
    type: "Claymore",
    rarity: 5,
    baseAtk: 674,
    lvl1BaseAtk: 48,
    subStat: { type: "energyRecharge", label: "Energy Recharge%", value: 36.8, baseValue: 8.0 },
    passiveName: "Sky-ripping Dragon Spine",
    passiveDesc: "Increases all DMG by 8~16%. After using an Elemental Burst, Normal or Charged Attacks create a vacuum blade that deals 80~160% of ATK as DMG to opponents along its path for 20s or 8 blades.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "skyward-pride-dmg", label: "All DMG Bonus (Skyward Pride)", stat: "dmgBonus", refinementValues: [8, 10, 12, 14, 16], isTeamBuff: false, computeCode: "(r) => [8, 10, 12, 14, 16][r - 1]" },
    ],
  },
  {
    name: "Skyward Spine",
    type: "Polearm",
    rarity: 5,
    baseAtk: 674,
    lvl1BaseAtk: 48,
    subStat: { type: "energyRecharge", label: "Energy Recharge%", value: 36.8, baseValue: 8.0 },
    passiveName: "Black Wing",
    passiveDesc: "Increases CRIT Rate by 8~16% and increases Normal ATK SPD by 12%. Normal and Charged Attacks on hit have a 50% chance to trigger a vacuum blade dealing 40~100% of ATK as DMG.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "skyward-spine-crit", label: "CRIT Rate% (Skyward Spine)", stat: "critRate", refinementValues: [8, 10, 12, 14, 16], isTeamBuff: false, computeCode: "(r) => [8, 10, 12, 14, 16][r - 1]" },
    ],
  },
  {
    name: "Song of Broken Pines",
    type: "Claymore",
    rarity: 5,
    baseAtk: 741,
    lvl1BaseAtk: 49,
    subStat: { type: "physicalDmgBonus", label: "Physical DMG Bonus%", value: 20.7, baseValue: 4.5 },
    passiveName: "Rebel's Banner-Hymn",
    passiveDesc: "Increases ATK by 16~32%. Normal/Charged Attacks grant Sigils of Whispers (max 4). At 4 Sigils, all party members gain Millennial Movement: Banner-Hymn (+12~24% Normal ATK SPD and +20~40% ATK for 12s).",
    isSupport: true,
    buffType: "both",
    mechanicDefs: [{ id: "pines-banner-active", label: "Banner-Hymn Active (4 Sigils)", control: "toggle", defaultValue: 1, hint: "Team buff: +12~24% Normal ATK SPD, +20~40% ATK for 12s" }],
    buffs: [
      { id: "pines-party-atk", label: "Party ATK% (Song of Broken Pines)", description: "Nearby party members gain +20~40% ATK", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: true, isPercent: true, conditionKey: "pines-banner-active", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['pines-banner-active'] ?? '1') === '1' || Number(ctx.inputs?.['pines-banner-active'] ?? 1) > 0; return on ? ([20, 25, 30, 35, 40][r - 1] / 100) * ctx.baseAtk : 0; }" },
      { id: "pines-self-atk", label: "Self ATK% (Song of Broken Pines Base)", stat: "atk", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([16, 20, 24, 28, 32][r - 1] / 100) * ctx.baseAtk" },
    ],
    signatureFor: ["eula"],
  },
  {
    name: "Splendor of Tranquil Waters",
    type: "Sword",
    rarity: 5,
    baseAtk: 542,
    lvl1BaseAtk: 44,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 88.2, baseValue: 19.2 },
    passiveName: "Dawn and Dusk by the Lake",
    passiveDesc: "When HP increases or decreases, Elemental Skill DMG is increased by 8~16% for 6s (max 3 stacks). When party members' HP increases or decreases, wielder's Max HP is increased by 14~28% for 6s (max 2 stacks).",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [
      { id: "splendor-skill-stacks", label: "Wielder HP Change Stacks (0-3)", control: "stacks", max: 3, defaultValue: 3, hint: "+8~16% Elemental Skill DMG per stack (up to +24~48%)" },
      { id: "splendor-hp-stacks", label: "Party Member HP Change Stacks (0-2)", control: "stacks", max: 2, defaultValue: 2, hint: "+14~28% Max HP per stack (up to +28~56%)" },
    ],
    buffs: [
      { id: "splendor-skill-dmg", label: "Elemental Skill DMG Bonus (Splendor)", stat: "skillDmgBonus", refinementValues: [24, 30, 36, 42, 48], isTeamBuff: false, conditionKey: "splendor-skill-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['splendor-skill-stacks'] ?? 3); return s * [8, 10, 12, 14, 16][r - 1]; }" },
      { id: "splendor-hp", label: "Max HP% (Splendor Party Stacks)", stat: "hp", refinementValues: [28, 35, 42, 49, 56], isTeamBuff: false, isPercent: true, conditionKey: "splendor-hp-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['splendor-hp-stacks'] ?? 2); return s * [14, 17.5, 21, 24.5, 28][r - 1]; }" },
    ],
    signatureFor: ["furina"],
  },
  {
    name: "Staff of Homa",
    type: "Polearm",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 66.2, baseValue: 14.4 },
    passiveName: "Reckless Cinnabar",
    passiveDesc: "HP increased by 20~40%. Additionally, provides an ATK Bonus based on 0.8~1.6% of the wielder's Max HP. When the wielder's HP is less than 50%, this ATK bonus is increased by an additional 1~1.8% of Max HP.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [
      { id: "homa-wielder-max-hp", label: "Character Max HP", control: "stacks", max: 100000, defaultValue: 35000, hint: "Max HP used for flat ATK bonus conversion" },
      { id: "homa-low-hp", label: "HP < 50% (+1.0~1.8% extra ATK)", control: "toggle", defaultValue: 1, hint: "Low HP ATK bonus trigger" },
    ],
    buffs: [
      { id: "homa-hp", label: "HP% (Staff of Homa)", stat: "hp", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
      { id: "homa-base-atk-from-hp", label: "Flat ATK from Max HP (Homa Base)", stat: "atk", refinementValues: [0.8, 1.0, 1.2, 1.4, 1.6], isTeamBuff: false, computeCode: "(r, ctx) => { const hp = Number(ctx.inputs?.['homa-wielder-max-hp'] ?? 35000); const ratio = [0.008, 0.01, 0.012, 0.014, 0.016][r - 1]; return hp * ratio; }" },
      { id: "homa-low-hp-atk", label: "Flat ATK from Max HP (Homa Low HP)", stat: "atk", refinementValues: [1.0, 1.2, 1.4, 1.6, 1.8], isTeamBuff: false, conditionKey: "homa-low-hp", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['homa-low-hp'] ?? '1') === '1' || Number(ctx.inputs?.['homa-low-hp'] ?? 1) > 0; if (!on) return 0; const hp = Number(ctx.inputs?.['homa-wielder-max-hp'] ?? 35000); const ratio = [0.01, 0.012, 0.014, 0.016, 0.018][r - 1]; return hp * ratio; }" },
    ],
    signatureFor: ["hu-tao"],
  },
  {
    name: "Staff of the Scarlet Sands",
    type: "Polearm",
    rarity: 5,
    baseAtk: 542,
    lvl1BaseAtk: 44,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 44.1, baseValue: 9.6 },
    passiveName: "Heat Haze at Horizon's End",
    passiveDesc: "The equipping character gains 52~104% of their Elemental Mastery as bonus ATK. When an Elemental Skill hits opponents, gain the Dream of the Scarlet Sands effect: gain 28~56% of their Elemental Mastery as bonus ATK for 10s. Max 3 stacks.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [
      { id: "scarlet-wielder-em", label: "Character EM", control: "stacks", max: 2000, defaultValue: 300, hint: "EM used for Scarlet Sands ATK conversion" },
      { id: "scarlet-dream-stacks", label: "Dream Stacks on Skill Hit (0-3)", control: "stacks", max: 3, defaultValue: 3, hint: "+28~56% of EM as additional ATK per stack" },
    ],
    buffs: [
      { id: "scarlet-base-em-to-atk", label: "Flat ATK from EM (Scarlet Sands Base)", stat: "atk", refinementValues: [52, 65, 78, 91, 104], isTeamBuff: false, computeCode: "(r, ctx) => { const em = Number(ctx.inputs?.['scarlet-wielder-em'] ?? 300); const ratio = [0.52, 0.65, 0.78, 0.91, 1.04][r - 1]; return em * ratio; }" },
      { id: "scarlet-stacks-em-to-atk", label: "Flat ATK from EM (Scarlet Sands Stacks)", stat: "atk", refinementValues: [84, 105, 126, 147, 168], isTeamBuff: false, conditionKey: "scarlet-dream-stacks", computeCode: "(r, ctx) => { const em = Number(ctx.inputs?.['scarlet-wielder-em'] ?? 300); const s = Number(ctx.inputs?.['scarlet-dream-stacks'] ?? 3); const perStack = [0.28, 0.35, 0.42, 0.49, 0.56][r - 1]; return em * s * perStack; }" },
    ],
    signatureFor: ["cyno"],
  },
  {
    name: "Starcaller's Watch",
    type: "Catalyst",
    rarity: 5,
    baseAtk: 542,
    lvl1BaseAtk: 44,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 88.2, baseValue: 19.2 },
    passiveName: "Starlight Navigation",
    passiveDesc: "Shield Strength is increased by 20~40%. When the wielder creates a shield or Geo Construct, All Elemental DMG Bonus is increased by 20~40% for 15s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "starcaller-elem-dmg", label: "All Elemental DMG Bonus (Starcaller's Watch)", stat: "dmgBonus", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
    ],
    signatureFor: ["kachina"],
  },
  {
    name: "Summit Shaper",
    type: "Sword",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "atkPct", label: "ATK%", value: 49.6, baseValue: 10.8 },
    passiveName: "Golden Majesty",
    passiveDesc: "Increases Shield Strength by 20~40%. Scoring hits on opponents increases ATK by 4~8% for 8s. Max 5 stacks. While protected by a shield, this ATK increase effect is increased by 100%.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [
      { id: "summit-stacks", label: "Golden Majesty Stacks (0-5)", control: "stacks", max: 5, defaultValue: 5, hint: "+4~8% ATK per stack" },
      { id: "summit-shielded", label: "Protected by Shield (2x ATK Buff)", control: "toggle", defaultValue: 1, hint: "Doubles ATK bonus from stacks" },
    ],
    buffs: [
      { id: "summit-atk", label: "ATK% (Summit Shaper Stacks)", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, conditionKey: "summit-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['summit-stacks'] ?? 5); const shielded = (ctx.inputs?.['summit-shielded'] ?? '1') === '1' || Number(ctx.inputs?.['summit-shielded'] ?? 1) > 0; const mult = shielded ? 2 : 1; return ((s * [4, 5, 6, 7, 8][r - 1] * mult) / 100) * ctx.baseAtk; }" },
    ],
  },
  {
    name: "Sunny Morning Sleep-In",
    type: "Catalyst",
    rarity: 5,
    baseAtk: 542,
    lvl1BaseAtk: 44,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 44.1, baseValue: 9.6 },
    passiveName: "Lazy Sun",
    passiveDesc: "Increases All Elemental DMG Bonus by 12~24%. Normal Attack hits grant 16~32% ATK for 10s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "sunny-morning-elem", label: "All Elemental DMG Bonus", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "sunny-morning-atk", label: "ATK%", stat: "atk", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([16, 20, 24, 28, 32][r - 1] / 100) * ctx.baseAtk" },
    ],
  },
  {
    name: "Surf's Up",
    type: "Catalyst",
    rarity: 5,
    baseAtk: 542,
    lvl1BaseAtk: 44,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 88.2, baseValue: 19.2 },
    passiveName: "Aqua-Bound Wave",
    passiveDesc: "Max HP is increased by 20~40%. Using an Elemental Skill grants 4 stacks of Scorching Summer: increases Normal Attack DMG by 12~24% per stack. Every 1.5s after Normal Attack hits, 1 stack is lost; after triggering Vaporize on an opponent, 1 stack is added. Max 4 stacks.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "surfs-up-stacks", label: "Scorching Summer Stacks (0-4)", control: "stacks", max: 4, defaultValue: 4, hint: "+12~24% Normal Attack DMG per stack (up to +48~96%)" }],
    buffs: [
      { id: "surfs-up-hp", label: "Max HP% (Surf's Up)", stat: "hp", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
      { id: "surfs-up-na-dmg", label: "Normal Attack DMG Bonus (Surf's Up)", stat: "normalDmgBonus", refinementValues: [48, 60, 72, 84, 96], isTeamBuff: false, conditionKey: "surfs-up-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['surfs-up-stacks'] ?? 4); return s * [12, 15, 18, 21, 24][r - 1]; }" },
    ],
    signatureFor: ["mualani"],
  },
  {
    name: "Symphonist of Scents",
    type: "Sword",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 33.1, baseValue: 7.2 },
    passiveName: "Fragrant Harmony",
    passiveDesc: "All Elemental DMG Bonus is increased by 12~24%. Normal and Charged Attacks dealing Elemental DMG increase ATK by 16~32% for 10s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "symphonist-elem-dmg", label: "All Elemental DMG Bonus", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "symphonist-atk", label: "ATK%", stat: "atk", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([16, 20, 24, 28, 32][r - 1] / 100) * ctx.baseAtk" },
    ],
  },
  {
    name: "The Daybreak Chronicles",
    type: "Catalyst",
    rarity: 5,
    baseAtk: 674,
    lvl1BaseAtk: 48,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 44.1, baseValue: 9.6 },
    passiveName: "Chronicle of Dawn",
    passiveDesc: "All Elemental DMG Bonus is increased by 12~24%. When an Elemental Burst is used, increases ATK by 20~40% for 12s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "daybreak-elem-dmg", label: "All Elemental DMG Bonus", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "daybreak-atk", label: "ATK%", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([20, 25, 30, 35, 40][r - 1] / 100) * ctx.baseAtk" },
    ],
  },
  {
    name: "The First Great Magic",
    type: "Bow",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 66.2, baseValue: 14.4 },
    passiveName: "Parsifal the Great",
    passiveDesc: "Charged Attack DMG increased by 16~32%. For every party member with the same Elemental Type as the wielder (including wielder), gain 1 Gimmick stack: ATK increased by 16/32/48% ~ 32/64/96%. For every member with a different type, gain 1 Theatrics stack: Movement SPD increased by 4/7/10% ~ 12/15/18%.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "great-magic-same-stacks", label: "Same-Element Party Members (1-3)", control: "stacks", max: 3, defaultValue: 3, hint: "+16/32/48% ATK for 1/2/3 matching element members" }],
    buffs: [
      { id: "great-magic-ca-dmg", label: "Charged Attack DMG Bonus (The First Great Magic)", stat: "chargedDmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
      { id: "great-magic-atk", label: "ATK% (The First Great Magic Stacks)", stat: "atk", refinementValues: [48, 60, 72, 84, 96], isTeamBuff: false, isPercent: true, conditionKey: "great-magic-same-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['great-magic-same-stacks'] ?? 3); const tiers: Record<number, [number, number, number, number, number]> = { 1: [16, 20, 24, 28, 32], 2: [32, 40, 48, 56, 64], 3: [48, 60, 72, 84, 96] }; const pct = (tiers[s] ?? tiers[3])[r - 1]; return (pct / 100) * ctx.baseAtk; }" },
    ],
    signatureFor: ["lyney"],
  },
  {
    name: "The Unforged",
    type: "Claymore",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "atkPct", label: "ATK%", value: 49.6, baseValue: 10.8 },
    passiveName: "Golden Majesty",
    passiveDesc: "Increases Shield Strength by 20~40%. Scoring hits on opponents increases ATK by 4~8% for 8s. Max 5 stacks. While protected by a shield, this ATK increase effect is increased by 100%.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [
      { id: "unforged-stacks", label: "Golden Majesty Stacks (0-5)", control: "stacks", max: 5, defaultValue: 5, hint: "+4~8% ATK per stack" },
      { id: "unforged-shielded", label: "Protected by Shield (2x ATK Buff)", control: "toggle", defaultValue: 1, hint: "Doubles ATK bonus from stacks" },
    ],
    buffs: [
      { id: "unforged-atk", label: "ATK% (The Unforged Stacks)", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, conditionKey: "unforged-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['unforged-stacks'] ?? 5); const shielded = (ctx.inputs?.['unforged-shielded'] ?? '1') === '1' || Number(ctx.inputs?.['unforged-shielded'] ?? 1) > 0; const mult = shielded ? 2 : 1; return ((s * [4, 5, 6, 7, 8][r - 1] * mult) / 100) * ctx.baseAtk; }" },
    ],
  },
  {
    name: "Thundering Pulse",
    type: "Bow",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 66.2, baseValue: 14.4 },
    passiveName: "Rule By Thunder",
    passiveDesc: "Increases ATK by 20~40% and grants Thunder Emblem stacks. At stack levels 1/2/3, Thunder Emblem increases Normal Attack DMG by 12/24/40% ~ 24/48/80%.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "thunder-emblem-stacks", label: "Thunder Emblem Stacks (0-3)", control: "stacks", max: 3, defaultValue: 3, hint: "+12/24/40% NA DMG bonus at R1 (up to +24/48/80% at R5)" }],
    buffs: [
      { id: "thundering-atk", label: "ATK% (Thundering Pulse)", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([20, 25, 30, 35, 40][r - 1] / 100) * ctx.baseAtk" },
      { id: "thundering-na-dmg", label: "Normal Attack DMG Bonus (Thunder Emblem)", stat: "normalDmgBonus", refinementValues: [40, 50, 60, 70, 80], isTeamBuff: false, conditionKey: "thunder-emblem-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['thunder-emblem-stacks'] ?? 3); const tiers: Record<number, [number, number, number, number, number]> = { 0: [0, 0, 0, 0, 0], 1: [12, 15, 18, 21, 24], 2: [24, 30, 36, 42, 48], 3: [40, 50, 60, 70, 80] }; return (tiers[s] ?? tiers[3])[r - 1]; }" },
    ],
    signatureFor: ["yoimiya"],
  },
  {
    name: "Tome of the Eternal Flow",
    type: "Catalyst",
    rarity: 5,
    baseAtk: 542,
    lvl1BaseAtk: 44,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 88.2, baseValue: 19.2 },
    passiveName: "Aeon Wave",
    passiveDesc: "HP is increased by 16~32%. When current HP increases or decreases, Charged Attack DMG is increased by 14~28% for 4s (max 3 stacks). At 3 stacks or when 3 stacks refresh, restore 8~12 Energy.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "aeon-wave-stacks", label: "Aeon Wave HP Change Stacks (0-3)", control: "stacks", max: 3, defaultValue: 3, hint: "+14~28% Charged Attack DMG per stack (up to +42~84%)" }],
    buffs: [
      { id: "tome-hp", label: "HP% (Tome of the Eternal Flow)", stat: "hp", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, isPercent: true, computeCode: "(r) => [16, 20, 24, 28, 32][r - 1]" },
      { id: "tome-charged-dmg", label: "Charged Attack DMG Bonus (Tome of Eternal Flow)", stat: "chargedDmgBonus", refinementValues: [42, 52.5, 63, 73.5, 84], isTeamBuff: false, conditionKey: "aeon-wave-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['aeon-wave-stacks'] ?? 3); return s * [14, 17.5, 21, 24.5, 28][r - 1]; }" },
    ],
    signatureFor: ["neuvillette"],
  },
  {
    name: "Tulaytullah's Remembrance",
    type: "Catalyst",
    rarity: 5,
    baseAtk: 674,
    lvl1BaseAtk: 48,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 44.1, baseValue: 9.6 },
    passiveName: "Bygone Azure Tear",
    passiveDesc: "Normal Attack SPD is increased by 10%. After using an Elemental Skill, Normal Attack DMG increases by 4.8~9.6% each second and by 9.6~19.2% after hitting opponents. Max increase is 48~96%.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "tulaytullah-na-buff", label: "Normal Attack DMG Bonus % (0-96%)", control: "stacks", max: 96, defaultValue: 48, hint: "Dynamic NA DMG buildup from skill (up to 48% at R1, up to 96% at R5)" }],
    buffs: [
      { id: "tulaytullah-na-dmg", label: "Normal Attack DMG Bonus (Tulaytullah)", stat: "normalDmgBonus", refinementValues: [48, 60, 72, 84, 96], isTeamBuff: false, conditionKey: "tulaytullah-na-buff", computeCode: "(r, ctx) => { const cap = [48, 60, 72, 84, 96][r - 1]; const input = Number(ctx.inputs?.['tulaytullah-na-buff'] ?? 48); return Math.min(input, cap); }" },
    ],
    signatureFor: ["wanderer"],
  },
  {
    name: "Uraku Misugiri",
    type: "Sword",
    rarity: 5,
    baseAtk: 542,
    lvl1BaseAtk: 44,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 88.2, baseValue: 19.2 },
    passiveName: "Brocade Bloom, Shrine Sword",
    passiveDesc: "Normal Attack DMG is increased by 16~32% and Elemental Skill DMG is increased by 24~48%. After a nearby active character deals Geo DMG, the aforementioned effects increase by 100% for 15s. Additionally, DEF is increased by 20~40%.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "uraku-geo-trigger", label: "Nearby Character Dealt Geo DMG (2x Buff)", control: "toggle", defaultValue: 1, hint: "Doubles NA and Skill DMG bonuses for 15s" }],
    buffs: [
      { id: "uraku-na-dmg", label: "Normal Attack DMG Bonus (Uraku Misugiri)", stat: "normalDmgBonus", refinementValues: [16, 20, 24, 28, 32], isTeamBuff: false, computeCode: "(r, ctx) => { const geo = (ctx.inputs?.['uraku-geo-trigger'] ?? '1') === '1' || Number(ctx.inputs?.['uraku-geo-trigger'] ?? 1) > 0; return [16, 20, 24, 28, 32][r - 1] * (geo ? 2 : 1); }" },
      { id: "uraku-skill-dmg", label: "Elemental Skill DMG Bonus (Uraku Misugiri)", stat: "skillDmgBonus", refinementValues: [24, 30, 36, 42, 48], isTeamBuff: false, computeCode: "(r, ctx) => { const geo = (ctx.inputs?.['uraku-geo-trigger'] ?? '1') === '1' || Number(ctx.inputs?.['uraku-geo-trigger'] ?? 1) > 0; return [24, 30, 36, 42, 48][r - 1] * (geo ? 2 : 1); }" },
      { id: "uraku-def", label: "DEF% (Uraku Misugiri)", stat: "def", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r) => [20, 25, 30, 35, 40][r - 1]" },
    ],
    signatureFor: ["chiori"],
  },
  {
    name: "Verdict",
    type: "Claymore",
    rarity: 5,
    baseAtk: 674,
    lvl1BaseAtk: 48,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 22.1, baseValue: 4.8 },
    passiveName: "Many Oaths of Dawn and Dusk",
    passiveDesc: "Increases ATK by 20~40%. When party members obtain Elemental Shards from Crystallize reactions, gain 1 Seal (max 2): increases Elemental Skill DMG by 18~36% per Seal.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [{ id: "verdict-seals", label: "Crystallize Seals (0-2)", control: "stacks", max: 2, defaultValue: 2, hint: "+18~36% Skill DMG per Seal (up to +36~72%)" }],
    buffs: [
      { id: "verdict-atk", label: "ATK% (Verdict)", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([20, 25, 30, 35, 40][r - 1] / 100) * ctx.baseAtk" },
      { id: "verdict-skill-dmg", label: "Elemental Skill DMG Bonus (Verdict Seals)", stat: "skillDmgBonus", refinementValues: [36, 45, 54, 63, 72], isTeamBuff: false, conditionKey: "verdict-seals", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['verdict-seals'] ?? 2); return s * [18, 22.5, 27, 31.5, 36][r - 1]; }" },
    ],
    signatureFor: ["navia"],
  },
  {
    name: "Vivid Notions",
    type: "Catalyst",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critRate", label: "CRIT Rate%", value: 33.1, baseValue: 7.2 },
    passiveName: "Vivid Dream",
    passiveDesc: "All Elemental DMG Bonus is increased by 12~24%. When an Elemental Burst is used, increases ATK by 20~40% for 12s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "vivid-elem-dmg", label: "All Elemental DMG Bonus", stat: "dmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "vivid-atk", label: "ATK%", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([20, 25, 30, 35, 40][r - 1] / 100) * ctx.baseAtk" },
    ],
  },
  {
    name: "Vortex Vanquisher",
    type: "Polearm",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "atkPct", label: "ATK%", value: 49.6, baseValue: 10.8 },
    passiveName: "Golden Majesty",
    passiveDesc: "Increases Shield Strength by 20~40%. Scoring hits on opponents increases ATK by 4~8% for 8s. Max 5 stacks. While protected by a shield, this ATK increase effect is increased by 100%.",
    isSupport: false,
    buffType: "self",
    mechanicDefs: [
      { id: "vortex-stacks", label: "Golden Majesty Stacks (0-5)", control: "stacks", max: 5, defaultValue: 5, hint: "+4~8% ATK per stack" },
      { id: "vortex-shielded", label: "Protected by Shield (2x ATK Buff)", control: "toggle", defaultValue: 1, hint: "Doubles ATK bonus from stacks" },
    ],
    buffs: [
      { id: "vortex-atk", label: "ATK% (Vortex Vanquisher Stacks)", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, conditionKey: "vortex-stacks", computeCode: "(r, ctx) => { const s = Number(ctx.inputs?.['vortex-stacks'] ?? 5); const shielded = (ctx.inputs?.['vortex-shielded'] ?? '1') === '1' || Number(ctx.inputs?.['vortex-shielded'] ?? 1) > 0; const mult = shielded ? 2 : 1; return ((s * [4, 5, 6, 7, 8][r - 1] * mult) / 100) * ctx.baseAtk; }" },
    ],
    signatureFor: ["zhongli"],
  },
  {
    name: "Whitelake Frostfeather",
    type: "Bow",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "critDmg", label: "CRIT DMG%", value: 66.2, baseValue: 14.4 },
    passiveName: "Frostfeather Gaze",
    passiveDesc: "Increases Cryo DMG Bonus by 12~24%. Aimed Shots increase ATK by 20~40% for 10s.",
    isSupport: false,
    buffType: "self",
    buffs: [
      { id: "frostfeather-cryo", label: "Cryo DMG Bonus", stat: "cryoDmgBonus", refinementValues: [12, 15, 18, 21, 24], isTeamBuff: false, computeCode: "(r) => [12, 15, 18, 21, 24][r - 1]" },
      { id: "frostfeather-atk", label: "ATK%", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([20, 25, 30, 35, 40][r - 1] / 100) * ctx.baseAtk" },
    ],
  },
  {
    name: "Wolf's Gravestone",
    type: "Claymore",
    rarity: 5,
    baseAtk: 608,
    lvl1BaseAtk: 46,
    subStat: { type: "atkPct", label: "ATK%", value: 49.6, baseValue: 10.8 },
    passiveName: "Wolfish Tracker",
    passiveDesc: "Increases ATK by 20~40%. On hit, attacks against opponents with less than 30% HP increase all party members' ATK by 40~80% for 12s. Can only occur once every 30s.",
    isSupport: true,
    buffType: "both",
    mechanicDefs: [{ id: "wgs-party-buff-active", label: "Target HP < 30% (+40~80% Party ATK)", control: "toggle", defaultValue: 1, hint: "Team buff: +40~80% ATK for 12s" }],
    buffs: [
      { id: "wgs-party-atk", label: "Party ATK% (Wolf's Gravestone)", description: "Attacks against enemies with <30% HP grant +40~80% ATK to all party members", stat: "atk", refinementValues: [40, 50, 60, 70, 80], isTeamBuff: true, isPercent: true, conditionKey: "wgs-party-buff-active", computeCode: "(r, ctx) => { const on = (ctx.inputs?.['wgs-party-buff-active'] ?? '1') === '1' || Number(ctx.inputs?.['wgs-party-buff-active'] ?? 1) > 0; return on ? ([40, 50, 60, 70, 80][r - 1] / 100) * ctx.baseAtk : 0; }" },
      { id: "wgs-self-atk", label: "Self ATK% (Wolf's Gravestone Base)", stat: "atk", refinementValues: [20, 25, 30, 35, 40], isTeamBuff: false, isPercent: true, computeCode: "(r, ctx) => ([20, 25, 30, 35, 40][r - 1] / 100) * ctx.baseAtk" },
    ],
  },
];

console.log("5-Star master definitions loaded.");
