import fs from "fs";
import path from "path";
import { ALL_246_WEAPONS } from "./master_definitions";

// List of all 246 names in exact order from the user's list
export const USER_246_NAMES = [
  // 5-Star (73)
  "A Teaspoon of Transcendence",
  "A Thousand Blazing Suns",
  "A Thousand Floating Dreams",
  "Absolution",
  "Amos' Bow",
  "Angelos' Heptades",
  "Aqua Simulacra",
  "Aquila Favonia",
  "Astral Vulture's Crimson Plumage",
  "Athame Artis",
  "Azurelight",
  "Beacon of the Reed Sea",
  "Bloodsoaked Ruins",
  "Calamity Queller",
  "Cashflow Supervision",
  "Crane's Echoing Call",
  "Crimson Moon's Semblance",
  "Disaster and Remorse",
  "Elegy for the End",
  "Engulfing Lightning",
  "Everlasting Moonglow",
  "Exaiphanes Blade",
  "Fang of the Mountain King",
  "Fractured Halo",
  "Freedom-Sworn",
  "Gest of the Mighty Wolf",
  "Golden Frostbound Oath",
  "Haran Geppaku Futsu",
  "Hunter's Path",
  "Jadefall's Splendor",
  "Kagura's Verity",
  "Key of Khaj-Nisut",
  "Light of Foliar Incision",
  "Lightbearing Moonshard",
  "Lost Prayer to the Sacred Winds",
  "Lumidouce Elegy",
  "Memory of Dust",
  "Mistsplitter Reforged",
  "Nightweaver's Looking Glass",
  "Nocturne's Curtain Call",
  "Peak Patrol Song",
  "Polar Star",
  "Primordial Jade Cutter",
  "Primordial Jade Winged-Spear",
  "Redhorn Stonethresher",
  "Reliquary of Truth",
  "Silvershower Heartstrings",
  "Skyward Atlas",
  "Skyward Blade",
  "Skyward Harp",
  "Skyward Pride",
  "Skyward Spine",
  "Song of Broken Pines",
  "Splendor of Tranquil Waters",
  "Staff of Homa",
  "Staff of the Scarlet Sands",
  "Starcaller's Watch",
  "Summit Shaper",
  "Sunny Morning Sleep-In",
  "Surf's Up",
  "Symphonist of Scents",
  "The Daybreak Chronicles",
  "The First Great Magic",
  "The Unforged",
  "Thundering Pulse",
  "Tome of the Eternal Flow",
  "Tulaytullah's Remembrance",
  "Uraku Misugiri",
  "Verdict",
  "Vivid Notions",
  "Vortex Vanquisher",
  "Whitelake Frostfeather",
  "Wolf's Gravestone",

  // 4-Star (139)
  "The Catch",
  "Ultimate Overlord's Mega Magic Sword",
  "Akuoumaru",
  "Alley Hunter",
  "Amenoma Kageuchi",
  "Ash-Graven Drinking Horn",
  "Ballad of the Boundless Blue",
  "Ballad of the Fjords",
  "Blackcliff Agate",
  "Blackcliff Longsword",
  "Blackcliff Pole",
  "Blackcliff Slasher",
  "Blackcliff Warbow",
  "Blackmarrow Lantern",
  "Blade of Atonement",
  "Calamity of Eshu",
  "Chain Breaker",
  "Cinnabar Spindle",
  "Clash of Kings",
  "Cloudforged",
  "Compound Bow",
  "Covenant of Frost and Snow",
  "Crescent Pike",
  "Dawning Frost",
  "Deathmatch",
  "Dialogues of the Desert Sages",
  "Dodoco Tales",
  "Dragon's Bane",
  "Dragonspine Spear",
  "Earth Shaker",
  "Echoes of the Heart",
  "Emberwell",
  "End of the Line",
  "Etherlight Spindlelute",
  "Eye of Perception",
  "Fading Twilight",
  "Favonius Codex",
  "Favonius Greatsword",
  "Favonius Lance",
  "Favonius Sword",
  "Favonius Warbow",
  "Festering Desire",
  "Finale of the Deep",
  "Flame-Forged Insight",
  "Fleuve Cendre Ferryman",
  "Flower-Wreathed Feathers",
  "Flowing Purity",
  "Flute of Ezpitzal",
  "Footprint of the Rainbow",
  "Forest Regalia",
  "Forged by the Golden Melody",
  "Frostbearer",
  "Frostbreath",
  "Fruit of Fulfillment",
  "Fruitful Hook",
  "Hakushin Ring",
  "Hamayumi",
  "Heretic's Molten Blade",
  "Ibis Piercer",
  "Iron Sting",
  "Jade Vista",
  "Kagotsurube Isshin",
  "Katsuragikiri Nagamasa",
  "King's Squire",
  "Kitain Cross Spear",
  "Lion's Roar",
  "Lithic Blade",
  "Lithic Spear",
  "Luxurious Sea-Lord",
  "Mailed Flower",
  "Makhaira Aquamarine",
  "Mappa Mare",
  "Master Key",
  "Missive Windspear",
  "Mitternachts Waltz",
  "Moonpiercer",
  "Moonweaver's Dawn",
  "Mountain-Bracing Bolt",
  "Mouun's Moon",
  "Oathsworn Eye",
  "Portable Power Saw",
  "Predator",
  "Prospector's Drill",
  "Prospector's Shovel",
  "Prototype Amber",
  "Prototype Archaic",
  "Prototype Crescent",
  "Prototype Rancour",
  "Prototype Starglitter",
  "Rainbow Serpent's Rain Bow",
  "Rainslasher",
  "Range Gauge",
  "Rightful Reward",
  "Ring of Yaxche",
  "Royal Bow",
  "Royal Greatsword",
  "Royal Grimoire",
  "Royal Longsword",
  "Royal Spear",
  "Rust",
  "Sacrificer's Staff",
  "Sacrificial Bow",
  "Sacrificial Fragments",
  "Sacrificial Greatsword",
  "Sacrificial Jade",
  "Sacrificial Sword",
  "Sapwood Blade",
  "Scion of the Blazing Sun",
  "Sequence of Solitude",
  "Serenity's Call",
  "Serpent Spine",
  "Snare Hook",
  "Snow-Tombed Starsilver",
  "Solar Pearl",
  "Song of Stillness",
  "Song of the Vigil",
  "Sturdy Bone",
  "Sword of Descension",
  "Sword of Narzissenkreuz Pneuma",
  "Talking Stick",
  "Tamayuratei no Ohanashi",
  "The Alley Flash",
  "The Bell",
  "The Black Sword",
  "The Dockhand's Assistant",
  "The Flute",
  "The Stringless",
  "The Viridescent Hunt",
  "The Widsith",
  "Tidal Shadow",
  "Toukabou Shigure",
  "Wandering Evenstar",
  "Wavebreaker's Fin",
  "Waveriding Whirl",
  "Whiteblind",
  "Windblume Ode",
  "Wine and Song",
  "Wolf-Fang",
  "Xiphos' Moonlight",

  // 3-Star (24)
  "Black Tassel",
  "Bloodtainted Greatsword",
  "Cool Steel",
  "Dark Iron Sword",
  "Debate Club",
  "Emerald Orb",
  "Ferrous Shadow",
  "Fillet Blade",
  "Halberd",
  "Harbinger of Dawn",
  "Magic Guide",
  "Messenger",
  "Otherworldly Story",
  "Raven Bow",
  "Recurve Bow",
  "Sharpshooter's Oath",
  "Skyrider Greatsword",
  "Skyrider Sword",
  "Slingshot",
  "Thrilling Tales of Dragon Slayers",
  "Traveler's Handy Sword",
  "Twin Nephrite",
  "White Iron Greatsword",
  "White Tassel",

  // 2-Star (5)
  "Iron Point",
  "Old Merc's Pal",
  "Pocket Grimoire",
  "Seasoned Hunter's Bow",
  "Silver Sword",

  // 1-Star (5)
  "Apprentice's Notes",
  "Beginner's Protector",
  "Dull Blade",
  "Hunter's Bow",
  "Waster Greatsword",
];

export function toSlug(name: string): string {
  return name
    .replace(/^["']|["']$/g, "")
    .toLowerCase()
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function toVarName(name: string): string {
  const slug = toSlug(name);
  return slug.replace(/-([a-z0-9])/g, (_, g) => g.toUpperCase());
}

console.log(`Loaded ${USER_246_NAMES.length} names.`);
